= Baris Batuhan- Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Recruit Me

---

== Overview

Recruit Me is a Java Desktop GUI application that is specifically designed for a recruiting agency for their processes about the candidates in their storage.

== Summary of contributions

* *Major enhancement*: added *filtering command*
** What it does: it filters the persons according to their every single aspect (Name, Phone, Email, Skills, ...), ait can manage multiple filtering at the same time and also the filter can be cleared in any time the user wants.
** Justification: This feature improves the usability of the product significantly, because it can eliminate al the candidates that are not fitting for the wanted job positions. Also it makes the searching and classification process easier for the app users.
** Highlights: This new feature affects all the commands already implemented and all other commands that will be implemented in the future. Thus, the interaction of this command with other commands are strongly investigated and minor changes for other  commands are also made to make the other commands compatible with filtering.

* *Major enhancement*: added *CV representation* for selected persons
** What it does: it shows the CV for selected person, if there is an available CV in the storage for that person. If there is not, it shows the placeholder page with the message: No CV is available.
** Justification: This feature gives the user a better chance to see more important information about the candidate easily. It is a nice-to-have feature.
** Highlights:
** Note: This feature has only a basic implementation. In the UserGuide, you can see what is included and what is planned to be done for v2.0.


* *Minor enhancement*:
** Some minor changes are made for the methods in AddressBook, ModelManager and VersionedAddressBook classes that AddCommand, DeleteCommand and EditCommand uses for the compatibility with filtering process:
** Fixed almost all failing system tests / GUI related tests / Edit Command tests in every update process of the process:
** Travis Checkstyle errors and some test errors are fixed:
** Updated README page and UI.png in each next step of the project:

== Other contributions:

* Contributions to the User Guide

** Filtering process is added to the User guide as a new section.
** The form of it, the usage and some examples are given for the user.
** For the newly implemented CV showing process, a section is added.
** About multiple person addition (planned for v2.0) a new section is added.
** Updated Add Command Section in User Guide.
** The changes can be seen in:
*** `UserGuide -> Features -> Filtering Recruit Me: filter` - include::UserGuide.adoc[tag=filter]
*** `UserGuide -> Features -> Filtering Recruit Me: filter clear` - include::UserGuide.adoc[tag=filterclear]
*** `UserGuide -> Features -> Filtering Recruit Me: filter reverse` - include::UserGuide.adoc[tag=filterreverse]
*** `UserGuide -> Features -> Showing and Updating the CV for a Person` - include::UserGuide.adoc[tag=cvview]
*** `UserGuide -> Features -> Adding Multiple Persons [coming in v2.0]` - include::UserGuide.adoc[tag=addmultiplepersons]

* Contributions to the Developer Guide

** A new section for filtering is added to the developer guide.
** Implementation of filtering process, other alternatives and implementation of tests are explained.
** Some of the use cases and user stories are updated.
** The changes can be seen in `DeveloperGuide -> Implementation -> Filter or/and/clear feature`

* Contributions to the README.doc

** Explanation of the application is updated.
** Some parts about the changes in every version is updated.
** UI.png is updated.
