= Baris Batuhan- Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Recruit Me

---

== Overview

Recruit Me is a Java Desktop GUI application that is specifically designed for a recruiting agency for their processes about the candidates in their storage.

== Summary of contributions

* *Major enhancement*: added *filtering command*
** What it does: it filters the persons according to their every single aspect (Name, Phone, Email, Skills, ...), ait can manage multiple filterings at the same time and also the filter can be cleared in any time the user wants.
** Justification: This feature improves the usability of the product significantly, because it can eliminate al the candidates that are not fitting for the wanted job positions. Also it makes the searching and classification process easier for the app users.
** Highlights: This new feature affects all the commands already implemented and all other commands that will be implemented in the future. Thus, the interaction of this command with other commands are strongly investigated and minor changes for other  commands are also made to make the other commands compatible with filtering.

* *Minor enhancement*:
** Some minor changes are made for the methods in AddressBook, ModelManager and VersionedAddressBook classes that AddCommand, DeleteCommand and EditCommand uses for the compatibility with filtering process.
** Travis Checkstyle errors and some test errors are fixed.

== Other contributions:

* Contributions to the User Guide

** Filtering process is added to the User guide in a new section.
** The form of it, the usage and some examples are given for the user.

include::../UserGuide.adoc[tag=filter]

* Contributions to the Developer Guide

** A new section for filtering is added to the developer guide.
** Implementation of filtering process, other alternatives and implementation of tests are explained.
** Some of the use cases and user stories are updated.

include::../DeveloperGuide.adoc[tag=filter]

* Contributions to the README.doc

** Explanation of the application is updated.
** Some parts about the changes in every version is updated.
** UI.png is updated.
