= Leong Yoke Yi Beatrice - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: RestOrRant

---

== About the project

RestOrRant is a project that was tasked to my team and I for a Software Engineering project. Given a basic command line
interface address book, we had the choice of enhancing or morphing it into a desktop application that caters to
specific users' needs.

My team and I chose to morph the address book into, RestOrRant (ROR), a restaurant management application for
restaurant managers, waiters and cashiers. It is designed for them to perform front-end operations more conveniently and
efficiently. ROR allows them to manage tables, orders, menu and statistical data using the Command Line Interface (CLI).

Constraints we had to work with: +

* It is assumed that users are familiar with Command Line Interfaces (CLI). +
* We had to adopt the coding style of the address book that was given to us. +
* A desktop application written in Java with around 10 kLoC. It also has a GUI created with JavaFX. +

My role encompasses managing the UI, project deadlines and any features related to the RestOrRant Statistics. This
include bill, revenue, menu item popularity, etc.

The following sections illustrates a detailed analysis of the enhancements.

== Summary of contributions
This is a summary of the coding, documentation and other helpful contributions to the team project.
* *Major enhancement*
** Calling for bill
** Calling for revenue
* *Minor enhancement*

. *Calling for bill*: added *the ability to calculate and record the bill of a specific table.*
** What it does: allows the user calculate and record the total bill accumulated from the table's orders.
** Justification: This feature is necessary to update the restaurant revenue, status of the specified tables and the
popularity of the menu items that were ordered.
** Highlights: This command is only usable in Table Mode.

. *Calling for revenue*: added *the ability to get revenue from the specified year, month and date*
** What it does: allows the user to get the required revenue the user specifies.
** Justification: This feature allows the restaurent manager to conveniently calculate and obtain the revenue
he/she wants. It also eliminates the possibility of human errors when calculating the revenue.
** Highlights: This command is only usable for dates, months and years that are valid. In the case where no
date, month or year is specified, the current day's revenue will be returned.

* *Minor enhancement*: Create a Bill Mode that displays a receipt for the user.

* *Code contributed*: Please refer to theses links to view my code +
[https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Ensures that the User Guide and Developer Guide are completed according to what was required.
*** Documents essential discussion pointers during meetings and share them with the team.
*** Informs team about the deadlines.

** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote tests for bill and statistics features (Pull requests https://github.com[#36], https://github.com[#38])

** Documentation:
*** Reorganise the User Guide according to modes: https://github.com/cs2103-ay1819s2-w09-3/main/pull/123[#123]

** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/cs2103-ay1819s2-w09-3/main/pull/167[#167],
https://github.comcs2103-ay1819s2-w09-3/main/pull/121[#121], https://github
.comcs2103-ay1819s2-w09-3/main/pull/121[#108]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide._
|===

include::../UserGuide.adoc[tag=bill]

include::../UserGuide.adoc[tag=statisticsmode]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide._
|===

include::../DeveloperGuide.adoc[tag=bill]

include::../DeveloperGuide.adoc[tag=statistics]

