= Leong Yoke Yi Beatrice - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: RestOrRant

---

== About the project

RestOrRant is a command line application that my team and I had to work on for a Software Engineering project.
Given a basic code for an address book, we had the choice of enhancing or morphing it into a desktop application that
 caters to specific users' needs.

We decided to morph it into RestOrRant (ROR), a restaurant management application for restaurant managers,
 waiters and cashiers. It is designed for them to perform front-end operations more efficiently like
 managing tables, handling orders, tracking the availability of menu items and calculating statistical data using the
 Command Line Interface (CLI).

RestOrRant is split into 4 main features: Tables, Orders, Menu and Statistics. To cater to needs of the user, modes
are created to make the application user-friendly. *Restaurant Mode*, *Table Mode*, *Menu Mode* and *Statistics Mode*
 are modes meant to handle these 4 features respectively. Each of my teammates are in charge of one feature and mine
 was Statistics. In the following sections, I will elaborate on my
contributions and extract relevant parts from the User Guide and Developer Guide that I wrote for the Statistics
feature.+

You may find it useful to refer to the table below for the different symbols and formatting used in this portfolio.

[width="70%",cols="^15%,85%"]
|===
a| `code` | Command that can be typed into the command box
ifdef::env-github[]
| :white_check_mark: | Expected result after executing the command
| :information_source: | Additional information that is good to know
| :heavy_exclamation_mark: | Important pointers to take note
endif::[]
ifndef::env-github[]
a| icon:check[role="green", size="2x"] | Expected result after executing the command
a| icon:info-circle[role="icon-note", size="2x"] | Additional information that is good to know
a| icon:exclamation-circle[role="icon-important", size="2x"] | Important pointers to take note
endif::[]
|===

== Summary of contributions

Overall, my role in this project encompasses managing the documentation of the project, keeping track the
deadlines and deliverable, enhancing and cleaning up the UI components and Statistics feature.
 You may refer below for a detailed summary of the coding, documentation and other helpful
contributions I have contributed to the team project.

. *Major enhancements:* I add *_Statistics feature_* and its relevant commands.

.. *Calling for bill*: `bill` command
** _What it does:_ It allows users to *calculate and record the total bill* accumulated from the table's order.
** _Justification:_ This feature is necessary to update the restaurant's revenue, status of the specified table and the
quantity of the menu items that were ordered.
** _Highlights:_ This command is only usable in Table Mode.

.. *Changing the Statistics Mode display*: `yearly`, `monthly`, `daily` commands
** _What it does:_ Changes the display to show yearly, monthly and daily *trends of the restaurant's earnings* as
well as the *popularity of the menu items*.
** _Justification:_ This feature allows the restaurant manager to study the restaurant performance. +
These makes it easier for the manager to make essential back-end and front-end management arrangements to cater to the days and
months that receives more customers. +
The popularity of the menu items also helps the manager decide what kind of
prior preparations are needed to cater to the popular dishes.
** _Highlights:_ At most 30 year, months or days along with its revenue are displayed to prevent overflow of data.

.. *Calling for revenue*: `revenue`, `revenue y/YEAR`, `revenue y/YEAR m/MONTH`, `revenue y/YEAR m/MONTH d/DAY`
** What it does: It allows users to *retrieve the required yearly, monthly, daily revenue* the user specifies.
** Justification: This feature allows the restaurant manager to conveniently calculate and obtain the revenue
he/she wants. It also eliminates the possibility of human errors when calculating the revenue.
** Highlights: This command is only usable for day, month, year that are valid and dates that exists in the calendar.
 In the case where no day, month and year are specified, the current day's revenue will be returned.

. *Minor enhancement*: Create a Bill Mode that displays a receipt for the user.

. *Code contributed*: Please refer to these links to view my code +
[https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=beesaycheese[Project
Code Dashboard]]

. *Other contributions*:

** Project management:
*** Ensures that the User Guide and Developer Guide are completed according to what was required.
*** Documents essential discussion pointers during meetings and share them with the team.
*** Use buffers to set deadlines and ensure everyone are informed and on task.

** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote tests for bill and statistics features (Pull requests https://github.com[#36], https://github.com[#38])

** Documentation:
*** Reorganise the User Guide according to modes: https://github.com/cs2103-ay1819s2-w09-3/main/pull/123[#123]

** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/cs2103-ay1819s2-w09-3/main/pull/167[#167],
https://github.comcs2103-ay1819s2-w09-3/main/pull/121[#121], https://github.comcs2103-ay1819s2-w09-3/main/pull/121[#108]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide._
|===

include::../UserGuide.adoc[tag=smintro]
Here are the commands that you can use in this mode to study the statistical data of your restaurant.

include::../UserGuide.adoc[tag=bill]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide._
|===

include::../DeveloperGuide.adoc[tag=statisticsclasses]

include::../DeveloperGuide.adoc[tag=statisticsstorage]

include::../DeveloperGuide.adoc[tag=bill]


