= Boston Cheong - Project Portfolio for Battleship
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project Overview

Hello! My name is Boston, a Year 2 Computer Science student at the National University of Singapore (NUS) team and I were presented with an existing code base for a command line interface(CLI) address book application.
We were tasked to enhance or morph the product in to a product of our own choice.
We chose to morph it into Battleship.

Battleship is a desktop game application based on the classic Battleship game.
The user interacts with it using a CLI and it has a graphical user interface(GUI) created using JavaFX.
It is written in Java, and has about 10 kLoC.

My role was to design and write the code for the `stats` feature of the game.
The following sections illustrate the feature in more detail, as well as the relevant sections I have added to the user and developer guides in relation to this feature.

== Summary of contributions

* *Major enhancement*: added *statistic feature of the game*
** *What it does*: The player can view information of their gameplay data any time during the duration of the game. This is enabled through a pop-up window that will display the relevant player data so far.
** *Justification*: The statistics feature is crucial to user experience in the game as it allows players to track and keep up with the progress of the game. It is also fundamental as a basis for deploying strategies in the gameplay.
** Highlights: [placeholder]
** Credits: [placeholder]

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Actively update issues and provide constructive comments and feedback to the team
*** Managed the progress of the Developer Guide and ensure it is completed on time
** Enhancements to existing features:
*** <Something on HistoryCommand> (Pull requests https://github.com[#], https://github.com[#])
** Documentation:
*** Setup the structure of the Developer Guide(https://github.com[#]) and updated the User Guide with relevant information for the `stats` command.
** Community:
*** PRs reviewed (with non-trivial review comments):
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=stats]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=stats]

---
