= Addison Ho's Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project Title: FomoFoto
=== Overview
My team and I were tasked with enhancing a basic command line addressbook for our Software Engineering project. We decided to morph the project into a image editor. +

FomoFoto is a robust yet simple image-editing tool. Users interact with the application through worded commands from their keyboard, and receive visual feedback from it through the displayed image on the application. +

Unlike other heavy image editors, FomoFoto has a very gentle learning curve as it abstracts out clutter by providing the more essential features (complex editing can still be done with special commands). The features and implementations are well documented in guides for users and developers respectively.

=== Summary of contributions

* *Major enhancement*: added *overall UI/UX design and interaction*.

** What it does: As a photo editor, it is pivotal for end-users to be able to see the images they are editing. Updates to the UI/UX allows for end-users to see their updates and image data in realtime. Adds an interface in the form of `Notifier` for components to interact with each other and draw updates to the UI.

** Justification: This feature comprise of five components, the init panel the image view, imported images panel, exif panel, and command history panel. The initpanel gives a detailed help message on application start. The image view is core to a photo editor for end-users to see the changes they making to their image. The three panels enhances to product significantly, by allowing users an intutive way to see all a) the images they have one in one look b) the exif data attached to that image and c) any command they have previously commited to the image.

** Highlights: This enhancement affects all exisiting commands that redraws the UI. This is in part due to the redesign of the overall UI and interface for components attached to it. The implementation is incredibly complex due the sheer number of UI elements working in tandem. Extensive research has been placed to ensure the UI remains as intuitive as possible i.e. hidding elements/image padding and color scheme to ensure end-users have the best user experience.

* *Major enhancement*: added *importing of images*.
** What it does: Allows for end-users to import any image into FomoFoto that they wish to edit. This can be done by means of a single file or an entire directory (non-recursive).

** Justification: This feature is core to the operation of FomoFoto. Without importing images, FomoFoto cannot run i.e. edit images sine there are no images in the system to modify.

** Highlights: This enhancement requires many checks to ensure the image is valid and the system can handle. For example, images that are two big will be reject by JavaFX. Images that are too large in size will also trigger a out-of-memory error. Images that do not fit the MIME image format are rejected since they cannot be edited not opened by the image panel.

* *Major enhancement*: added *Image Class*.
** What it does: Breaksdown any opened image into a reusable, extensible Image object with helper fields and methods.

** Justification: This feature allows for other operations to utilize any imported image more efficiently since it is hard to parse the raw image format. The creation of this feature also allows for each image to manage its own edit history therby allowing the functionality of redo and undo.

** Highlights: This enhancement affects all files being imported into FomoFoto. This means any command interacting with images in the system should conform to the Image class and its fields. The fields include validation checks to ensure the fields being created are valid for an image object.

* *Minor enchancement*: Added a Tab Command. The inclusion of the Tab Command allows GUI-less interaction of the information panel.
* *Minor enchancement*: Added Album Class. The inclusion of the singleton Album Class allows for components to interact with `assets` folder with a single method call.
* *Minor enchancement*: Added a sample image folder. The folder comprises of a large list of `valid` and `invalid` images that can be further used for code testing and feature testing.

* *Code contributed*: [https://github.com/CS2103-AY1819S2-W14-2/main/commits?author=carrein[List of commits]].

* *Other contributions*:

** Project management:
*** Managed releases `v1.0, v1.1, v1.2` (3 releases) on GitHub.

** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34]).
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#--], https://github.com[#--]).

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#--].

** Community:

*** Core PRs reviewed: https://github.com[#75], https://github.com[#45].
*** Core Issues raised: https://github.com[#109], https://github.com[#149], https://github.com[#78], https://github.com[#32], https://github.com[#77], https://github.com[#76], https://github.com[#43].

** Tools:
*** Integrated a third party library (Google's Guava) to the project (https://github.com[#--]).
*** Integrated TravisCI to the team repo.
*** Integrated Coveralls to the team repo.
*** Added Issue temples to the team repo.

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
