= Chen Wen - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: The Real App

---

== Overview

*The Real App* is an enhanced desktop address book APP. The enhanced application enables the *real estate agents* to store large amount of customer contacts, together with property information; provide fleet retrieval commands among tons of property information; and utilize storage better to provide reminder, archive and corresponding features. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

|===
|This section shows a summary of my coding, documentation, and other helpful contributions to the team project.
|===

* *Major enhancement*: implement *the pin/unpin feature*
** What it does: The *pin* command allows the user to pin some contacts from the normal contact list and put it into the new created pin list. The user may reverse this change with *undo* command. The *unpin* command do reverse as its name shows and the change can also be reversed with *undo* command.
** Justification: This feature improves the product significantly because a user can put important contacts on top of the whole list, which can save much time for searching.
** Highlights: This enhancement does not affect existing commands as well as future commands. Since the pin list is apart from the original one and works as a fast and detailed look-up manual towards someone the agent currently working with or extremely important contacts. The most challenging part is about the connection requires to build between the brand-new storage for pin list and the other parts. Another point is the UI part displayed in the main window.

* *Minor enhancement*: Apply *undo* command to the new commands. So user can directly use *undo* to change the state of address book and pin list to the former one.

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=chenwencuhk[Project Code Dashboard]]

* *Other contributions*:

** Documentation:
*** Make improvements to the existing User Guide and Developer Guide to make it more reader friendly.
** Community:
*** PRs reviewed (with non-trivial review comments).


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=pinunpinfeatures]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=pinunpinfeatures]

