= Arielyte Tsen Chung Ming - Project Portfolio
:site-section: AboutUs
:toc:
:toc-title: Project Portfolio
:toc-placement: preamble
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets
:sourceDir: ../src/main/java
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S2-W11-3/main
:websiteURL: https://cs2103-ay1819s2-w11-3.github.io/main
:source-highlighter: rouge
:doctype: article
:reproducible:

= PROJECT: TravelBuddy
---
== Overview

This document serves to highlight my contributions to *TravelBuddy*, a travel log application that allows users to efficiently manage their travel records, i.e. the places that they have visited. Additional features built into TravelBuddy allows them to search through the records, attach photos and view statistical models. This  link:{websiteURL}/AboutUs.html[team-based] project is part of the CS2103T Software Engineering module in National University of Singapore, in which my team and I were tasked to morph a given link:https://se-education.org/addressbook-level4/[address book] product into a new product -- TravelBuddy. The complete source code for TravelBuddy is available on link:{repoURL}[GitHub].

My role was to design the chart feature. The following sections describe the enhancements I made in greater detail. They also include relevant sections from the user and developer guide related to these enhancements.

== Summary of Contributions

This section summarizes my contribution to this project.

=== Major Enhancement
The major enhancement I did was adding the ability to generate charts in real-time or via the `generate` command, the details of which are stated below:

*What it does:* It allows users to generate charts based on their travel data that they have accumulated in TravelBuddy.

*Justification:* This feature allows users to gather insights into their travel patterns. It improves the user-friendliness of TravelBuddy while giving it additional functionality. As such, this feature is the differentiating factor for TravelBuddy among other travel log products on the market.

*Highlights:* The complexity of this enhancement is due to the fact that it links up with all the components of the existing architecture, as described below:

* *Logic:* The chart feature can be activated via the `generate` command. Hence, a parser is required to parse the command.
* *Model:* Any changes made to the travel records has to be reflected in the charts. Hence, relevant data is extracted from the latest version of the travel records.
* *Storage:* The extracted data has to be stored into the charts' respective JSON files.
* *User Interface (UI):* The charts have to be displayed to the users.

The enhancement required an in-depth analysis of various design alternatives. The challenge was to redesign the architecture to suit the enhancement while still maintaining the integrity of other existing commands and features.

*Credits:* link:https://github.com/google/gson[Gson], a third-party library, was used in the enhancement of this product to convert Java Objects into JSON and back.

*Code contributed to the major enhancement*: [link:https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=chung-ming&sort=displayName&since=2019-02-10&timeframe=day&reverse=false&repoSort=true[RepoSense]] [link:{repoURL}/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Achung-ming+-label%3Atype.MinorEnhancement+-label%3Atype.Testing[Functional code]] [link:{repoURL}/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Achung-ming+label%3Atype.Testing[Test code]]

=== Minor Enhancement

The minor enhancement I did was converting the `add` command's `Email` parameter in the previous address book product to a `Description` parameter in the current product. The `Description` parameter allows users to note down their thoughts about the specific place that they have visited.

Additionally, I added command aliases to new and existing commands so users have the option to input a shorter command.

*Code contributed to both minor enhancements*: [link:https://github.com/CS2103-AY1819S2-W11-3/main/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Achung-ming+label%3Atype.minorEnhancement[Functional code]]

=== Other Contributions

The details of other contributions can be found in <<OtherContributions>> below:

[[OtherContributions]]
[width="100%", cols="20%,<80%", reftext="Table 2.3.1", caption="Table 2.3.1: "]
.Details of Other Contributions
|=======================================================================

|*Project management*
|Managed releases on GitHub (Releases: link:{repoURL}/releases/tag/v1.2[`v1.2`], link:{repoURL}/releases/tag/v1.2.1[`v1.2.1`], link:{repoURL}/releases/tag/v1.3.1[`v1.3.1`] and link:{repoURL}/releases/tag/1.4[`v1.4`])

|*Enhancements to existing features*
a|* Updated the Graphical User Interface's (GUI) color scheme to link:{repoURL}/blob/master/src/main/resources/view/LightTheme.css[`LightTheme.css`] (Pull request: link:{repoURL}/pull/88[#88])

|*Documentation*
a|* Improved readability to existing contents of the User Guide +
(Pull request: link:{repoURL}/pull/165[#165]) +
* Added {websiteURL}/UserGuide.html#command-glossary-and-shortcuts[Command Glossary and Shortcuts] to the User Guide +
(Pull request: link:{repoURL}/pull/163[#163])
* Added {websiteURL}/DeveloperGuide.html#user-stories[user stories], {websiteURL}/DeveloperGuide.html#use-cases[use cases] and {websiteURL}/DeveloperGuide.html#non-functional-requirements[non-functional requirements] to the Developer Guide (Pull requests: link:{repoURL}/pull/170[#170] and link:{repoURL}/pull/192[#192])

|*Community*
a|* Reviewed a teammates' pull requests (with non-trivial review comments) +
(Pull request: link:{repoURL}/pull/115#discussion_r271991549[#115]) +
* Contributed to the forum discussions +
(Example: link:https://github.com/nus-cs2103-AY1819S2/forum/issues/37#issuecomment-474714683[1]) +
* Reported bugs and suggestions for other teams +
(Examples:
https://github.com/cs2103-ay1819s2-w14-4/main/issues/144#issue-429813664[1],
https://github.com/cs2103-ay1819s2-w14-4/main/issues/139#issue-429808212[2],
https://github.com/cs2103-ay1819s2-w14-4/main/issues/134#issue-429801329[3],
https://github.com/cs2103-ay1819s2-w14-4/main/issues/131#issue-429798816[4],
https://github.com/cs2103-ay1819s2-w14-4/main/issues/129#issue-429796558[5],
https://github.com/cs2103-ay1819s2-w14-4/main/issues/123#issue-429791114[6],
https://github.com/cs2103-ay1819s2-w14-4/main/issues/120#issue-429789451[7],
https://github.com/cs2103-ay1819s2-w14-4/main/issues/117#issue-429786916[8] and
https://github.com/cs2103-ay1819s2-w14-4/main/issues/110#issue-429781005[9])

|*Tools*
a|* Integrated a third-party library (Gson) to the project +
(Pull request: {repoURL}/pull/80[#80]) +
* Integrated a new GitHub plugin (link:https://www.codacy.com/[Codacy]) to the team repository +
(Pull request: {repoURL}/pull/113[#113])

|=======================================================================

== Contributions to the User Guide

The original User Guide was updated to match the enhancements implemented in this project.

****
_Given below is the start of the excerpt of sections I contributed to the link:{websiteURL}/UserGuide.html[User Guide]. They showcase my ability to write documentation targeting end-users._
****

//include::../UserGuide.adoc[tag=intro]
//include::../UserGuide.adoc[tag=features]
include::../UserGuide.adoc[tag=generate]
//include::../UserGuide.adoc[tag=cheatsheet]
//include::../UserGuide.adoc[tag=commandGlossaryAndShortcuts]

****
_This is the end of the excerpt of the link:{websiteURL}/UserGuide.html[User Guide]._
****

== Contributions to the Developer Guide

The original Developer Guide was updated to match the enhancements implemented in this project.

****
_Given below is the start of the excerpt of sections I contributed to the link:{websiteURL}/DeveloperGuide.html[Developer Guide]. They showcase my ability to write documentation targeting end-users._
****

//include::../DeveloperGuide.adoc[tag=implementation]
include::../DeveloperGuide.adoc[tag=chartFeature]
//include::../DeveloperGuide.adoc[tag=user-stories]
//include::../DeveloperGuide.adoc[tag=use-cases]

****
_This is the end of the excerpt of the link:{websiteURL}/DeveloperGuide.html[Developer Guide]._
****
