= Daniel Greenhouse - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Recruit Me

---

== Overview

Recruit Me is a desktop application designed for . It is an adaptation of AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to sort persons alphabetically*
** What it does: allows the user to sort the list of persons alphabetically based on their name.
** Justification: This feature improves the product by taking a first step to adapting the address book to Recruit Me. It also opens the possibility of further sorting methods once the person becomes more advanced (can contain more parameters).
** Highlights: This enhancement is fully compatible with undo and redo commands.

* *Minor enhancement*: _{To be added at a later date}_.

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=sort]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=sort]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
