= Evan Tay - Project portfolio for BrainTrain +
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:
:repoURL: https://github.com/CS2103-AY1819S2-W14-1/main
:pullURL: https://github.com/CS2103-AY1819S2-W14-1/main/pull/
:seeduURL: https://github.com/se-edu/addressbook-level4
:webURL: https://cs2103-ay1819s2-w14-1.github.io/main/

== Introduction +
The purpose of this portfolio is to demonstrate my software engineering competency by showcasing my code and documentation contributions to the link:{repoURL}[BrainTrain project].

=== Overview +
The BrainTrain project was developed by a team of 5 students over seven weeks, under the National University of Singapore's link:{seeduURL}[CS2103T: Software Engineering module]. +

CS2103T students were given the option of enhancing an link:{seeduURL}[existing addressbook application] or morphing it into another product. We chose to morph it into a https://en.wikipedia.org/wiki/Spaced_repetition[spaced-repetition] card application because we wanted to further challenge ourselves and improve our software engineering skills.

=== What is BrainTrain +

BrainTrain is a *spaced-repetition card application* which makes *memorizing easy and effective*. With BrainTrain's link:https://www.theguardian.com/education/2016/jan/23/spaced-repetition-a-hack-to-make-your-brain-store-information[Spaced Repetition System (SRS)] optimizing your card revision intervals, you will be able to *learn more in less time*.

{empty} +

== Summary of contributions +
My primary responsibility was to design and develop the *Card Management System*. My secondary responsibility was to act as the project's *documentation lead*. In the following sub-sections, you will find a summary of my key contributions to the project.

=== Major enhancement +
My largest contribution to the project was the implementation of the *Card Management System*: +

* Context: In BrainTrain, each lesson contains a set of cards of the same type and topic.
* What it does: It provides users with the ability to add, edit and delete lessons in *Lesson View* and *Card View* modes.
* In *Lesson View*, users can:
** Add and delete lessons by using the `addLesson` and `deleteLesson` commands
** Open a lesson in *Card View* for editing by using the `edit` command
** List the full details of all lessons by using the `listLessons` command
* In *Card View*, users can:
** Add and delete cards by using the `addCard` and `deleteCard` commands
** Set the 2 test values to be tested in quiz mode for all cards in the lesson by using the `set` command
** List the full details of all cards by using the `listCards` command
** Quit *Card View* and return to *Lesson View* by using the `quit` command
* Justification: Users need to be able to create and manage content in order to use BrainTrain for card learning.
* Most significant pull requests: link:{pullURL}113[#113], link:{pullURL}173[#173] and link:{pullURL}180[#180]
* Code contributed: https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=digipie[View on RepoSense] +

=== Minor enhancement +
My second largest contribution was the Graphical User Interface (GUI) representation for the Card Management System: +

* What it does: Displays all lessons and their relevant details in *Lesson View*, and the details and cards of the lesson being edited in *Card View*.
** In *Lesson View*, users can view all lessons and their details (e.g. number of cards).
** In *Card View*, users can view the opened lesson's details and its cards.
* Justification: The GUI representation of lessons and cards provides users with the ability to view all relevant details at a glance.
* Code contributed: https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=digipie[View on RepoSense] +

=== Other contributions +
In addition to designing and writing code, I also contributed to the project through the following means:

* *Documentation:*
As the documentation lead, I ensured overall quality for the project's documentation by,
** Writing the User Guide's Introduction and Quick Start sections (see link:{pullURL}15[#15], link:{pullURL}85[#85], and link:{pullURL}180[#180]).
** Editing the User Guide and Developer Guide for overall coherency as editor (see
link:{pullURL}20[#20], https://github.com/CS2103-AY1819S2-link:{pullURL}85[#85], and link:{pullURL}180[#180]).
* *Project management:* I assisted the team lead, <<eugenefdw#, Eugene>> by,
** Managing product releases link:{repoURL}/releases/tag/v1.2.1[v1.2.1] and link:{repoURL}/releases/tag/v1.3[v1.3.0].
** Coordinating team for milestone link:{repoURL}/milestone/4[v1.3].
* *Software architecture:* I contributed to the overall project by,
** Performing major refactor of `seedu.address.logic` and `seedu.address.model.util` package structure and design to improve workflow for entire team (see  link:{pullURL}/85[#85], link:{pullURL}/180[#180]).
** Co-designing the app's light and dark theme with fellow developer <<halcyoneee#, Tze Ting>> (see link:{pullURL}180[#180]).
* *Community:* I worked with my team to resolve problems together by,
** Assisting teammates in fixing their bugs (see link:{pullURL}33[#33] and link:{pullURL}97[#97]).
** Reviewing teammates' pull requests with constructive feedback (see link:{pullURL}37[#37], link:{pullURL}139[#139] and link:{pullURL}175[#175]).

{empty} +

== Contributions to the user guide +
I have listed some of my key contributions to the link:{webURL}UserGuide.html[user guide] as excerpts below: +

=== Excerpt: Quick start +
_Click link:{webURL}UserGuide.html#Quick-start[here] to view this section in the user guide._

=== Excerpt: Adding a lesson: `addLesson` +
_Click link:{webURL}UserGuide.html#addLesson[here] to view this section in the user guide._

=== Excerpt: Setting the lesson's test pair: `set` +
_Click link:{webURL}UserGuide.html#set[here] to view this section in the user guide._

=== Excerpt: Deleting a card: `deleteCard` +
_Click link:{webURL}UserGuide.html#deleteCard[here] to view this section in the user guide._

{empty} +

== Contributions to the developer guide +
I have listed some of my key contributions to the link:{webURL}DeveloperGuide.html[developer guide] as excerpts below: +

=== Excerpt: How do the key components interact +
_Click link:{webURL}DeveloperGuide.html#componentInteractions[here] to view this section in the developer guide._

=== Excerpt: How do the logic sub-components interact +
_Click link:{webURL}DeveloperGuide.html#logicInteractions[here] to view this section in the developer guide._

=== Excerpt: Management feature +
_Click link:{webURL}DeveloperGuide.html#mgtFeature[here] to view this section in the developer guide._
