= Donald Lee - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Know-It-All

---

== Overview

Know-It-All is a flashcard application that helps students manage, store, and use flash cards effectively. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.
My major roles included the report feature and ability to record score.

== Summary of contributions
|===
|_Below is a summary of my coding, documentation, and other helpful contributions to the team project._
|===

* *Major enhancement*: added the *ability to generate scoring report for card folder*
** What it does: Collates the scoring data of cards in the folder and generates a report for that folder that shows performance change.
** Justification: This feature improves the product significantly because a user can see the outcome of the spaced-repetition technique employed by Know-It-All. They are able to track their average score over time, per folder, so that
they are able tell which folders they score well and not so well for.
** Highlights: This enhancement has a graph showing the last 10 test session scores. A percentage change in scoring
between the last and second last test session is also shown.

* *Major enhancement*: added *the ability to sort by scoring performance*
** What it does: allows the user to sort the cards by scoring performance. Other features can make use of this feature by using any appropriate comparator.
** Justification: This feature improves the product significantly because many other features can be built on top of this one.
** Highlights: This enhancement affects the existing list. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changing the way cards are naturally ordered.

* *Minor enhancement*: Added State to Model Component's to represent user's "location" in the application. This removes edge cases of commands being executed illegally, i.e. where they otherwise shouldn't be.

* *Minor enhancement*: added a score attribute that allows the application to track the number of correct and incorrect attempts for individual cards.

* *Code contributed*: [https://github.com/cs2103-ay1819s2-w10-4/main/pull/75[ability to sort]] [https://github.com/cs2103-ay1819s2-w10-4/main/pull/46[add score attribute]][https://github.com/cs2103-ay1819s2-w10-4/main/pull/97[add report]]

* *Other contributions*:

** Enhancements to existing features:
*** Wrote additional tests for new features to increase coverage from 80% to 82% (Pull requests https://github.com/cs2103-ay1819s2-w10-4/main/pull/75[#75])

** Documentation:
*** Rewrote the project README: https://github.com/cs2103-ay1819s2-w10-4/main/pull/107[#107]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/cs2103-ay1819s2-w10-4/main/pull/57[#57], https://github.com/cs2103-ay1819s2-w10-4/main/pull/49[#49], https://github.com/cs2103-ay1819s2-w10-4/main/pull/72[#72], https://github.com/cs2103-ay1819s2-w10-4/main/pull/129[#129]
** Tools:
*** Integrated Github plugins Travis CI, AppVeyor and Coveralls to the team repo: https://github.com/cs2103-ay1819s2-w10-4/main/pull/2[#2]

== Contributions to the User Guide
|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=reportoperations]
include::../UserGuide.adoc[tag=sortcommand]

== Contributions to the Developer Guide
|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
include::../DeveloperGuide.adoc[tag=report]
include::../DeveloperGuide.adoc[tag=state]
include::../DeveloperGuide.adoc[tag=reportusecase]
