= Lee Tze Ting - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

== PROJECT: BrainTrain

This project portfolio page showcases my contributions to the BrainTrain project.

== Overview

BrainTrain is a spaced repetition flashcard application which makes memorizing easy and efficient.
Research has shown that the Spaced-Repetition System (SRS) is more effective than traditional
memorization techniques. With it, you will be able to learn more with less time. User interaction
happens through Command Line Interface (CLI) and it has a minimal Graphical User Interface (GUI)
created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Quiz mode

** *What it does*: Quiz mode manages user interaction during a quiz. It comprises of 4 commands
only available in quiz mode and takes in all other inputs as answer.

** *Justification*: To ensure that answers are not limited or excluded of certain keywords,
BrainTrain supports two different modes, management and quiz mode. To differentiate the
commands between the two modes, quiz mode commands start with a backslash `\`, whereas management
commands are not.

** *Highlights*: Pull request https://github.com/CS2103-AY1819S2-W14-1/main/pull/32[#32],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/43[#42],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/96[#96],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/108[#108],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/129[#129]

* *Minor enhancement*:

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]

* *Other contributions*:

** Project management:
*** Managed release `v1.1` on GitHub
*** Integrated `AddressBook` features with `BrainTrain` ( https://github.com/CS2103-AY1819S2-W14-1/main/pull/33[#33])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=quiz]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=quiz]
