= Lee Tze Ting - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

== PROJECT: BrainTrain

This project portfolio page showcases my coding, documentation and other contributions to the BrainTrain project.

== Overview

As a student of the CS2103T: Software Engineering module, I was tasked with working with 4 other students as a team to build a product from an existing https://github.com/se-edu/addressbook-level4[address book application] over 7 weeks. We were given a choice to morph the existing address book to any application we want and we chose to develop *BrainTrain* to further challenge ourselves.

BrainTrain is a spaced repetition flashcard application which makes memorizing easy and efficient. User interaction happens through Command Line Interface (CLI) and it has a minimal Graphical User Interface (GUI)
created with JavaFX. It is written in Java, and has about 16 kLoC.

My role was to design and build the app's quiz mode. The following sections detail what I have contributed to the project, and showcases my ability to write user and developer documentation.

== Summary of contributions

* *Major enhancement*: Implementation of quiz mode

** *What it does*: Quiz mode manages user interaction during a quiz. It comprises of 6 commands
which are only available in this mode. It also reads in answer inputs.

*** `[ANSWER]...` - Answers the current question. All inputs without the prefix `\` are treated as answers.
*** `\difficult` - Labels current question in quiz as difficult or not.
*** `\help` - Lists all commands in quiz and inputs the program will accept.
*** `\hint` - Reveals additional information to help user to solve the question.
*** `\quit` - Quits a quiz and save attempted progress.
*** `\status` - Lists current status and lesson progress of user.

** *Justification*: Users need to be able to launch a lesson in quiz mode, where they will be tested on the lesson's flashcards, in order to use BrainTrain for memorization.

** *Highlights*: Pull request https://github.com/CS2103-AY1819S2-W14-1/main/pull/32[#32],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/43[#42],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/96[#96],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/129[#129],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/175[#175],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/186[#186]

* *Minor enhancement*: Implementation of quiz mode display to user.

** *What it does*: In order to cater for two different mode, there will be 2 different display.
Display will switch smoothly between management mode and quiz mode.

** *Justification*: This is to ensure that there is no unnecessary display to distract the user during a quiz mode.
The user just need to focus solely on going through the flashcard without having to care about
the list of lesson available.

** *Highlights*: Pull request
https://github.com/CS2103-AY1819S2-W14-1/main/pull/108[#108]

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=halcyoneee[RepoSense]]

* *Other contributions*:

** Project management:
*** Managed 3 out of 6 releases `v1.1`, `v1.3.1` and `v1.4` on GitHub

** Team contribution:
*** Integrated `AddressBook` features with `BrainTrain` (https://github.com/CS2103-AY1819S2-W14-1/main/pull/33[#33])
*** Improved test coverage from 88% to 95% by writing all the BrainTrain system tests (https://github.com/CS2103-AY1819S2-W14-1/main/pull/175[#175])
*** Implemented `ChangeThemeCommand` to change between light and dark theme which persists beyond
app restart. (https://github.com/CS2103-AY1819S2-W14-1/main/pull/175[#175])

** Documentation:
*** Updated Architecture, Logic, UI and QuizModel component diagram to match the current
implementation. (https://github.com/CS2103-AY1819S2-W14-1/main/pull/186[#186])

** Community:
*** Reviewed pull requests with constructive feedback
(examples: https://github.com/CS2103-AY1819S2-W14-1/main/pull/30[#30],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/85[#87],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/97[#97],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/121[#121])

*** Contributed to forum discussions
(examples: https://github.com/nus-cs2103-AY1819S2/forum/issues/49[#49],
https://github.com/nus-cs2103-AY1819S2/forum/issues/51[#51])

*** Reported bugs and suggestion for other team in the class
(examples: https://github.com/cs2103-ay1819s2-w09-1/main/issues/106[#106],
https://github.com/cs2103-ay1819s2-w09-1/main/issues/118[#118],
https://github.com/cs2103-ay1819s2-w09-1/main/issues/140[#140])

*** Assisted <<digipie#, Evan>> in adding a legend footer to his management mode (https://github.com/cs2103-ay1819s2-w09-1/main/issues/106[#106])

== Contributions to the User Guide

|===
|_Given below is an extract of my contributions to the https://cs2103-ay1819s2-w14-1.github.io/main/UserGuide.html[user guide]._
|===

_Start of extract of quiz mode_
include::../UserGuide.adoc[tag=quiz]
_End of extract of quiz mode_

== Contributions to the Developer Guide

|===
|_Given below is an extract of my contribution to the https://cs2103-ay1819s2-w14-1.github.io/main/DeveloperGuide.html[developer guide]._
|===

_Start of extract of quiz mode_

include::../DeveloperGuide.adoc[tag=quiz]
_End of extract of quiz mode_
