= Lee Tze Ting - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

== PROJECT: BrainTrain

This project portfolio page showcases my contributions to the BrainTrain project such as coding,
documentation and other contributions.

== Overview

BrainTrain is a spaced repetition flashcard application which makes memorizing easy and efficient.
Research has shown that the Spaced-Repetition System (SRS) is more effective than traditional
memorization techniques. With it, you will be able to learn more with less time. User interaction
happens through Command Line Interface (CLI) and it has a minimal Graphical User Interface (GUI)
created with JavaFX. It is written in Java, and has about 10 kLoC.

My role in BrainTrain is to design and manage the app's quiz mode. The following sections
give a summary of how I have contributed to the project and showcases my ability to write both
the user and developer guide.

== Summary of contributions

* *Major enhancement*: Implementation of quiz mode

** *What it does*: Quiz mode manages user interaction during a quiz. It comprises of 6 commands
which are only available in quiz mode. Quiz mode also reads in answer inputs.

** *Justification*: To ensure that answers are not limited or excluded of certain keywords,
BrainTrain supports two different modes, management and quiz mode. To differentiate the
commands between the two modes, quiz mode commands start with a backslash `\`, whereas management
commands are not.

** *Highlights*: Pull request https://github.com/CS2103-AY1819S2-W14-1/main/pull/32[#32],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/43[#42],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/96[#96],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/108[#108],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/129[#129],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/175[#175]

* *Minor enhancement*: Implementation of quiz mode display to user and changing between the
two dark and light theme.

** *What it does*: In order to cater for two different mode, there will be 2 different display.
Display will switch smoothly between management mode and quiz mode. For users that prefers light
over dark theme, they can choose either one easily that persists beyond app restart.

** *Justification*: This is to ensure that there is no unnecessary display to distract the user during a quiz mode.
The user just need to focus solely on going through the flashcard without having to care about
the list of lesson available.

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=halcyoneee[RepoSense]]

* *Other contributions*:

** Project management:
*** Managed 2 out of 4 releases `v1.1` and `v1.4` on GitHub

** Team contribution:
*** Integrated `AddressBook` features with `BrainTrain` (https://github.com/CS2103-AY1819S2-W14-1/main/pull/33[#33])
*** Wrote system tests to increase coverage from 88% to 95% (https://github.com/CS2103-AY1819S2-W14-1/main/pull/175[#175])

** Documentation:
*** Updated class and sequence diagrams to match the current implementation

** Community:
*** PRs reviewed with comments:
(examples: https://github.com/CS2103-AY1819S2-W14-1/main/pull/30[#30],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/85[#87],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/97[#97],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/121[#121])

*** Contributed to forum discussions
(examples: https://github.com/nus-cs2103-AY1819S2/forum/issues/49[#49],
https://github.com/nus-cs2103-AY1819S2/forum/issues/51[#51])

*** Reported bugs and suggestion for other team in the class
(examples: https://github.com/cs2103-ay1819s2-w09-1/main/issues/106[#106],
https://github.com/cs2103-ay1819s2-w09-1/main/issues/118[#118],
https://github.com/cs2103-ay1819s2-w09-1/main/issues/140[#140])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

_Start of extract of quiz mode_
include::../UserGuide.adoc[tag=quiz]
_End of extract of quiz mode_

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=quiz]
