= Tay Hui Chun - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:icons: font

== Project: Health Hub
My team and I were tasked with enhancing a basic command line interface addressbook application for one of our modules CS2103T
- Software Engineering. We have decided to morph it into an application that handles patient-request tasks such as the registering
of new requests from patients and health workers.

The primary purpose of this application is for the hospital administrative staff to register
new requests onto the system, and assign suitable health workers to the patients. As such, qualitative data such as the
patient's conditions are also recorded within the system, and vice versa for the skillset of the health workers.

My role in the team was to handle the User Interface (UI) programming and render the desired display to the user who will be using the
application. It involves a little bit of User Experience (UX) when writing code to structure the design of the different UI components
that are interacting with one another. Other than writing code, I also wrote tests in the form of component, integration and
system tests that will test for different user behaviors when they are using the app. In addition, I extended the text input from the app
to introduce an autocomplete feature for the users to easily select from the list of suggested commands, as well the `setreminder`
feature that will also relieve some of the work that the user has to do (such as remembering to contact the patients).

== Overview
* Restructured most of the `.fxml` files associated with the UI components
* Wrote code to render the model data into the different UI components
* Wrote my own version of stylesheet to use for the app
* Handle logic for displaying a request's details in the `InfoPanel`, which is the center panel of the app.
* Extended the normal textfield to an additional autocomplete functionality.
* Added a `setreminder` command

== Summary of Contributions

* *Major Enhancement 1*: restructured the original AB4 UI code into different code that will suit the context of our app (Health Hub) .
** What it does: Shows the lists of requests and health workers in two different panels. The app has a center panel to render the selection display of a request.
** Justification: This is important as it is the interface that the user will be interacting with. Important details such as a patient's name and NRIC are displayed differently
compared to the other details such as address. Special noteworthy details such as the conditions of a patient or the skills of a health worker are also displayed differently.
** Highlights: In addition to rendering the model data, the details of a request is displayed in the center panel of the app, accompanied with a map that will show the location of the patient's home.
** Credits: Myself, but integrated a UI library called `font-awesome` in the app itself to render the display of icons related to request details. The static map is from `gothere.sg`.

* *Major Enhancement 2*: added the ability for the user to select from a list of suggested commands, which is also known as an autocomplete feature.
** What it does: Shows a list of suggestions based on the character that the user has typed in the text input.
** Justification: This is important as new users might be lost as to what type of commands they can use. By having an autocomplete feature, they spend shorter time
rewriting the same commands (e.g. adding 10 requests).
** Highlights: The autocomplete feature, although useful, has caused some non-deterministic type behavior for the user. E.g. sometimes the text box does not register a key `DOWN` event.
** Credits: Myself, but had read some tutorials online on how to do it.

* *Minor Enhancement*: added a `setreminder` command to further enhance the app's capability, by reminding the user of a task he or she needs to do within the day.

* *Code Contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other Contributions*:

** Project Management:
*** Assigned the relevant issues to my teammates and suggested solutions for them to resolve it (Issues https://github.com/CS2103-AY1819S2-W09-2/main/issues/188[#188],
https://github.com/CS2103-AY1819S2-W09-2/main/issues/190[#190],
https://github.com/CS2103-AY1819S2-W09-2/main/issues/195[#195])
** Enhancements to existing features:
*** Wrote the system tests that integrate newly implemented features to increase coverage from 82% to 90% (Pull requests https://github.com/CS2103-AY1819S2-W09-2/main/pull/209[#209],
https://github.com/CS2103-AY1819S2-W09-2/main/pull/217[#217],
https://github.com/CS2103-AY1819S2-W09-2/main/pull/219[#219])
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Reported bugs and suggestions for other teams in the class (examples: https://github.com/nus-cs2103-AY1819S2/pe-dry-run/issues/221[1],
https://github.com/nus-cs2103-AY1819S2/pe-dry-run/issues/355[2])

== Contributions to the User Guide

|===
|_The sections below demonstrate how I used an emphathetic approach to educate the users of Health Hub on its features and future releases._
|===

include::../UserGuide.adoc[tag=releasenotes-2.0]

include::../UserGuide.adoc[tag=setreminder]

|===
|_The table below demonstrates the importance of formatting key information for my users,
so that they can easily find the summary of the commands._
|===

include::../UserGuide.adoc[tag=summary]

== Contributions to the Developer Guide

|===
|_The sections below showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=ui-header]

include::../DeveloperGuide.adoc[tag=setreminder]

include::../DeveloperGuide.adoc[tag=autocomplete]


== Project: PayMe

---

