= Tay Zhan Peng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FomoFoto

---

== Overview

My team and I were tasked with enhancing a basic command line addressbook for our Software Engineering project. We decided to morph the project into a image editor. +

FomoFoto is a robust yet simple image-editing tool. Users interact with the application through worded commands from their keyboard, and receive visual feedback from it through the displayed image on the application. +

Unlike other heavy image editors, FomoFoto has a very gentle learning curve as it abstracts out clutter by providing the more essential features (complex editing can still be done with special commands). The features and implementations are well documented in guides for users and developers respectively.

In addition, FomoFoto is well-maintained with high reliability and code quality as it is covered by rigorous tests and checks.

== Summary of contributions
This section provides a summary of my coding, documentation and other contributions to FomoFoto, our team project.

=== *Major Enhancement* -- Ability to open files

** What is does: It allows users to open an image that was previously imported into the album for editing.

** Justification: This feature is essential as it sets up the application to allow image manipulation and image filters commands to work. Upon using the `open` command, the image is displayed prominently in the main window of the application, allowing users to confirm and know which image they are currently editing.  

** Highlights: This enhancement requires in depth analysis on how the temporary image is stored. It retrieves the opened image from `assets` folder and creates two copies of it in `temp` folder named `ori_img.png` and `temp_img.png`. Subsequent edits will update and replace the `temp_img.png`. The `ori_img.png` is utilised during an `undo` or `redo`. The implementation was challenging as it required many changes to the `Model` to ensure components access only folders that they are related to. 

** *Code contributed*: [https://github.com/CS2103-AY1819S2-W14-2/main/commits?author=itszp[List of commits]]

=== *Other contributions*:

** Project management:
*** Managed release `v1.2` and `v1.3` (2 releases) on GitHub
** Documentation:
*** Wrote features implemented for the User Guide: https://github.com/CS2103-AY1819S2-W14-2/main/issues/132[#132]
*** Wrote model and features for the Developer Guide: https://github.com/CS2103-AY1819S2-W14-2/main/pull/129 [#129]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103-AY1819S2-W14-2/main/pull/39[#39]
*** Reported bugs and provided solutions to team: https://github.com/CS2103-AY1819S2-W14-2/main/issues/103[#103], https://github.com/CS2103-AY1819S2-W14-2/main/issues/93[#93], https://github.com/CS2103-AY1819S2-W14-2/main/pull/39[#39], https://github.com/CS2103-AY1819S2-W14-2/main/issues/70[#70], https://github.com/CS2103-AY1819S2-W14-2/main/issues/89[#89]
** Tools:
*** Integrated a third party library (https://github.com/sksamuel/scrimage[`scrimage`]) to the project (https://github.com[#42])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=BlackWhiteCommand]

include::../UserGuide.adoc[tag=ContrastCommand]

include::../UserGuide.adoc[tag=BrightnessCommand]

include::../UserGuide.adoc[tag=CommandSummary]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=LogicComponentSequenceDiagrams]

include::../DeveloperGuide.adoc[tag=StorageComponent]

include::../DeveloperGuide.adoc[tag=ImageFilter]


== PROJECT: PowerPointLabs

