= Jerald Tan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: BrainTrain

This project portfolio page showcases my contributions to the BrainTrain project such as coding,
documentation and other contributions.

My role in BrainTrain is to design and manage the app's user data. The following sections
give a summary of how I have contributed to the project and showcases my ability to write both
the user and developer guide.

== Overview

BrainTrain is a spaced repetition flashcard application which makes memorising key learning concepts easy and efficient.
BrainTrain uses Spaced-Repetition System (SRS), a more effective and efficient memorisation technique compared to hardcore
memorisation techniques. Users will be able to learn more with less time. User interaction
happens through Command Line Interface (CLI) and it has a minimal Graphical User Interface (GUI)
created with JavaFX. It is written in Java, and has about 10 kLoC.

My role in BrainTrain is to design and manage the app's user data. The following sections
give a summary of how I have contributed to the project and showcases my ability to write both
the user and developer guide.

== Summary of contributions

* *Major enhancement*: User features, Comma-Separated Values(CSV) File Storage

** *What it does*: User features manage the user progress and import and export their progress into a simple CSV file accordingly.
This feature is automated.
Import of user file happens when the application is opened
Export of user file happens when the application is closed

** *Why is it important*: In consideration of the portability for users to use BrainTrain across different devices, it is
important to have a file to keep track of the status of the questions. Furthermore, each question will have a unique SRS-date that is
dependent on how well the user answered the questions. Questions with approaching due dates will be listed first.


** *Highlights*: Pull request https://github.com/CS2103-AY1819S2-W14-1/main/pull/30[#30],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/75[#75],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/106[#106],
https://github.com/CS2103-AY1819S2-W14-1/main/pull/139[#139],

* *Minor enhancement*: Sanitise user inputs of the CSV file that is generated

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=jeraldtsy[RepoSense]]

* *Other contributions*:
** Documentation:
*** Updated class and sequence diagrams to match the current implementation
*** Reported bugs and suggestion for other team in the class
(examples: https://github.com/CS2103-AY1819S2-W16-1/main/issues/172[#172],
https://github.com/CS2103-AY1819S2-W16-1/main/issues/163[#163],
https://github.com/CS2103-AY1819S2-W16-1/main/issues/143[#143],
https://github.com/CS2103-AY1819S2-W16-1/main/issues/152[#152])

== Contributions to the User Guide

include::../UserGuide.adoc[tag=jeraldtsy]

== Contributions to the Developer Guide

include::../DeveloperGuide.adoc[tag=datastorage]


