= Jerald Tan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: BrainTrain

This project portfolio page showcases my contributions to the BrainTrain project.

== Overview

BrainTrain is a spaced repetition flashcard application which makes memorizing easy and efficient.
Research has shown that the Spaced-Repetition System (SRS) is more effective than traditional
memorization techniques. With it, you will be able to learn more with less time. User interaction
happens through Command Line Interface (CLI) and it has a minimal Graphical User Interface (GUI)
created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: User features, CSV File Storage

** *What it does*: User features manage the user progress and import and export their progress into a CSV file accordingly. The feature is automated whenever the program is open(Import) or close(export)

** *Highlights*: https://github.com/CS2103-AY1819S2-W14-1/main/pull/86(86)
https://github.com/CS2103-AY1819S2-W14-1/main/pull/30[#30]

* *Minor enhancement*:

* *Code contributed*: [https://github.com/CS2103-AY1819S2-W14-1/main/pull/30[Functional code]] [https://github.com/CS2103-AY1819S2-W14-1/main/pull/86[Functional code]] [https://github.com/CS2103-AY1819S2-W14-1/main/pull/120[Test code]] _{give links to collated code files}_

