= Jia Hao Lim - TeethHub Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: TeethHub

In a Software Engineering module, my team was given the task to morph the given AddressBook 4 into an application of our choice. The result was TeethHub.

=== Overview

TeethHub is designed for Dentists who prefer type commands over clicking on a Graphical User Interface(GUI). It is still possible to perform some actions by clicking on the GUI, but only in very limited capacity. For example, the user can select patients and records by clicking on them, but they would need to type the edit commands to edit them.

As of version 1.4: +
TeethHub allows Dentists to manage patient information, records of each patient and tasks for the dentist. TeethHub can also export them to a PDF file. +
TeethHub displays the latest teeth information in the form of an image that follows the *Universal Numbering System* dental notation.
TeethHub displays statistics generated from all patients and records stored in it.

The GUI of TeethHub is created with JavaFX. TeethHub is written in Java, and has about 20,000 lines of code. +
TeethHub was morphed from AddressBook 4, which had about 10,000 lines of code.

=== Summary of contributions

* *Major enhancement*: Added *the ability to open/import/save/export external .json files*
** What it does:
`Open` allows the user to replace the TeethHub contents with the contents of a *.json file of their choice*. The .json file must be a .json file that was saved/exported using TeethHub.
`Import` allows the user to add *contents of their choice* of a *.json file of their choice* to the TeethHub contents. The .json file must be a .json file that was saved/exported using TeethHub.
`Save` allows the user to save all contents of TeethHub to an external .json file.
`Export` allows the user to save *contents of their choice* of TeethHub to an external .json file.
** Justification: This feature improves the product significantly because the user can store and access multiple different databases. +
E.g. The user may save different databases of patients depending on which clinic he saw them. +
E.g. Different users may share an account on the same computer. Each user may choose to use a different database.
** Highlights: The code for reading and writing .json files was already implemented in AddressBook 4, in the form of an auto-load on start and auto-save on exit. However there was no way for the user to manually make use of that, short of closing TeethHub, replacing TeethHub.json and then re-opening TeethHub every time they wished to open another file. Furthermore, the user could not specify the patients they wished to access/save. This enhancement allows the users this choice and required an analysis of design alternatives.
** Credits: AddressBook 4's code for reading and writing .json files.

* *Major enhancement*: Added *the ability to save/export external .pdf files*
** What it does: Allows the user to save/export PDF files which was more reader friendly when not using TeethHub.
** Justification: This feature improves the product significantly because the user can view/print a more comprehensible version of their patients' data during/for the times when they have no access to TeethHub, as opposed to opening/printing a .json file.
** Highlights: As opposed to the first enhancement, the code for reading and writing .pdf files was *not* implemented in AddressBook 4. The code for processing the data for PDF printing had to be coded from scratch. The writing and printing was done with the help of a third-party library, Apache PDFBox.
** Credits: Apache PDFBox for writing and saving .pdf files.

* *Minor enhancement*: Added shortcuts to the longer commands. E.g. Enter `padd` or `patientadd` to add a Patient.
* *Minor enhancement*: Added Suggestion commands that advises the user when they input a "common" command. +
E.g. The user enters `add`. TeethHub will ask them if they meant `patientadd` or `recordadd` or `taskadd`, depending on the context.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*: 
** Contributions to other members' enhancements: 
*** Came up with idea of the Copy feature.

** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com/CS2103-AY1819S2-W17-2/main/pull/198[#198], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage by 6%~7% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]

*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
** Tools:
*** Integrated a third party library (Apache PDFBox) to the project (https://github.com[#42])

_{you can add/remove categories in the list above}_

=== Contributions to the User Guide


|====
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|====

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

=== Contributions to the Developer Guide

|====
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|====

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]
