= Chong Kay Heen - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FomoFoto

=== 1. Overview of the Project
My team and I were tasked with enhancing a basic command line AddressBook for our Software Engineering project. We decided to morph the project into an image editor. +

FomoFoto is a robust yet simple image-editing tool. Users interact with the application through worded commands from their keyboard, and receive visual response through the displayed image on the application. Unlike other heavy image editors, FomoFoto has a gentle learning curve as it removes clutter by providing the more essential features. The features and implementations are well documented in guides for users and developers respectively. In addition, FomoFoto is well-maintained with high reliability and code quality as it is covered by rigorous tests and checks.

'''
=== 2. Summary of Contributions
This section provides a summary of my coding, documentation and miscellaneous contributions to FomoFoto, our team project.

* *Major Enhancement*: I added *image manipulation commands*.

** _What it does:_ This feature allows users to manipulate images on a physical level, such as rotating, cropping and resizing the target image. Users key in keywords like `rotate`, `crop` and `resize` to activate the respective commands.

** _Justification:_ This feature improves the product significantly because it is an essential feature of an image editor. Users might want to `rotate` their images because the orientation is wrong or `crop` out certain unwanted parts in the image. Should the image be too large, users can `resize` it as well.

** _Highlights:_ This enhancement works with all other commands, including the image filters that were implemented by my teammate. An in-depth analysis of the commands were done before we decided to make use of a library. The implementation was challenging because there was a need to coordinate between the image filter commands and the commands here, because the two libraries returned different objects. There was a need to ensure that the `Image` class and `CurrentEdit` class could accept changes from both libraries.

** _Credits:_ https://github.com/rkalla/imgscalr[`ImgScalr Library`]

* *Major Enhancement*: I added a *watermark command*.

** _What it does:_ This feature allows users to add a watermark (any words or numbers) with the © sign to the target image. Users key in the keyword `wm` to activate this command.

** _Justification:_ This feature improves the product significantly because it helps users such as professional photographers protect their images after editing it on our image editor. The copyright watermark prevents unauthorised third parties from using the images for their own private purposes.

** _Highlights:_ It was especially challenging to integrate this command with all other commands acting on the same image, because a watermark should only be added once to an image. This implied that we had to ensure that the `Image` class contains a flag that indicates the presence of a watermark on the image, and this flag had to be constantly updated accurately in every command that can possibly add or remove a watermark from an image, which includes the `WaterMark` command, `SetPreset` command and `undo/redo` commands.

* *Minor Enhancement*: I added a feature where the `Image` returns a file type (e.g. JPEG, PNG), because the methods to edit images differ according to the file type.

* *Code Contributed*: https://github.com/CS2103-AY1819S2-W14-2/main/commits?author=kayheen[List of commits], https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=kay%20heen%20&sort=displayName&since=2019-02-10&until=2019-04-15&timeframe=day&reverse=false&repoSort=true[Project Code Dashboard]

* *Other Contributions*:

** Project Management:
*** Ensured that we were on task with our project documentation by allocating roles and ensuring consistency with our words and diagrams. (User Guide and Developer Guide)
*** Integrated Codacy to our GitHub repository: https://github.com/CS2103-AY1819S2-W14-2/main/pull/249[#249]

** Enhancements to Existing Features:
*** Wrote tests for image manipulation and watermark commands to increase coverage: https://github.com/CS2103-AY1819S2-W14-2/main/pull/188[#188], https://github.com/CS2103-AY1819S2-W14-2/main/pull/208[#208], https://github.com/CS2103-AY1819S2-W14-2/main/pull/222[#222]

** Documentation:
*** Did the Developer Guide architecture and sequence diagrams for the overall application: https://github.com/CS2103-AY1819S2-W14-2/main/pull/84[#84], https://github.com/CS2103-AY1819S2-W14-2/main/pull/118[#118]
*** Did the Developer Guide documentation for image manipulation and watermark commands: https://github.com/CS2103-AY1819S2-W14-2/main/pull/59[#59], https://github.com/CS2103-AY1819S2-W14-2/main/pull/123/[#123], https://github.com/CS2103-AY1819S2-W14-2/main/pull/229[#229], https://github.com/CS2103-AY1819S2-W14-2/main/pull/234[#234]
*** Did the User Guide documentation for image manipulation and watermark commands: https://github.com/CS2103-AY1819S2-W14-2/main/pull/61/[#61], https://github.com/CS2103-AY1819S2-W14-2/main/pull/120/[#120], https://github.com/CS2103-AY1819S2-W14-2/main/pull/221[#221]
*** Did the the User Guide documentation for the overall walk through: https://github.com/CS2103-AY1819S2-W14-2/main/pull/65[#65]

** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S2-W14-2/main/pull/220[#220], https://github.com/CS2103-AY1819S2-W14-2/main/pull/235[#235], https://github.com/CS2103-AY1819S2-W14-2/main/pull/238[#238], https://github.com/CS2103-AY1819S2-W14-2/main/pull/239[#239]
*** Reported bugs and suggestions for other teams in the class:  https://github.com/CS2103-AY1819S2-W16-2/main/issues/102[#102], https://github.com/CS2103-AY1819S2-W16-2/main/issues/112[#112],
https://github.com/CS2103-AY1819S2-W16-2/main/issues/115[#115],
https://github.com/CS2103-AY1819S2-W16-2/main/issues/117[#117],

** Tools:
*** Integrated a third party library (ImgScalr) to the project (https://github.com/CS2103-AY1819S2-W14-2/main/pull/26[#26])

=== 3. Contributions to the User Guide

|===
|_The sections below are my contributions to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

==== 3.1 Crop an Image : `crop`
'''
include::../UserGuide.adoc[tag=CropCommand]

==== 3.2 Rotate an Image : `rotate`
'''

include::../UserGuide.adoc[tag=RotateCommand]

==== 3.3 WaterMark : `wm`
'''
include::../UserGuide.adoc[tag=WaterMarkCommand]

==== 3.4 Other contributions
'''
* A Walk Through of the Image Editor
* Resize Command

=== 4. Contributions to the Developer Guide

|===
|_The sections below are my contributions to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

==== 4.1 How the Architecture Components Interact with Each Other
'''
include::../DeveloperGuide.adoc[tag=ArchiInteraction]

==== 4.2 Image Manipulation
'''
include::../DeveloperGuide.adoc[tag=ImageManipulation]

==== 4.3 WaterMark Feature
'''
include::../DeveloperGuide.adoc[tag=WaterMark]

==== 4.4 Other Contributions
'''
* Crop Command
* Resize Command
* Architecture Diagrams
