= Kok Jia Xuan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: In-Credit-Ble

---

== Overview

This portfolio describes my contributions to a software engineering project called _In-Credit-Ble_.

_In-Credit-Ble_ is a finance tracker application, morphed from an address book application, and created by 4 other friends and me.
With _In-Credit-Ble_, you can set budgets, allocate budgets to categories, record your expenses etc.

Abiding by the project constraints, _In-Credit-Ble_ is designed for users who prefer typing over mouse/voice commands.
All of _In-Credit-Ble_’s functions can be accomplished using the keyboard.

In this project, I mainly worked on implementing _In-Credit-Ble_’s `sort` and `reverse` features.
The following sections explain these enhancements in more detail, and also show the relevant sections I have added to _In-Credit-Ble_’s user and developer guide on these features.

The figure below explains the symbols and formatting used in this document

[frame=none, grid=none]
|===
|`-NAME` | Words in `UPPER_CASE` are parameters to be supplied by the user (e.g. `sort -NAME`)
|`[ORDER]` | Words in square brackets are optional
|`SortCommandParser#parse()| `parse()` method in `SortCommandParser`
|===

== Summary of contributions

This section contains a description of some enhancements I made, and a summary of my contributions.


=== Enhancement added

I added a `sort` command and a `reverse` command in _In-Credit-Ble_.

* *What they do*: +
The `reverse` command allows users to reverse the list of entries displayed on the graphic user interface.
The `sort` command allows users to sort the entries by name, amount, date and category, in both ascending order and descending order.


* *Justification*: +
Without the `sort` command, entries will be displayed in an order where the most recently entered entry is at the bottom of the list.
However, this may not be very helpful and user-friendly to the user. A user may want to sort the entries by amount,
so that he/she can find out what he/she has been spending the most on. A user may also want to sort entries by name, date and category to make the list more organised. +
The `reverse` command will allow the user to reverse the list as a user may want to view the entries in the opposite order.
For example, after sorting the entries by amount in descending order, a user may want the entries to be sorted by amount in ascending order next,
and this can be achieved conveniently using the `reverse` command.


* Highlights: +
These enhancements work with existing commands such as `edit` and `delete`. When a list is sorted,
it may be easier to find an entry (_In-Credit-Ble_ has a `search` function too!).
These enhancements are also compatible with _In-Credit-Ble_’s `undo` and `redo` functions.


=== Code contributed
Click https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=kjiaxuan[here] to see the code I contributed to the _In-Credit-Ble_ project!


=== Other contributions
* Enhancements:
** Added aliases for the earlier commands and allowed commands entered to be case-insensitive so that the software
becomes more user-friendly and convenient to use. +
(Pull Requests: https://github.com/CS2103-AY1819S2-W17-3/main/pull/15[#15],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/22[#22],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/71[#71])
** Imported DateTimeFormatter and LocalDate into the project to make management of dates easier. +
(Pull Requests: https://github.com/CS2103-AY1819S2-W17-3/main/pull/90[#90])
** Worked on debugging the system tests and increased code coverage. +
(Pull Requests: https://github.com/CS2103-AY1819S2-W17-3/main/pull/177[#177])

* Documentation:
** Updated and formatted parts of User Guide and Developer Guide. +
(Pull Requests: https://github.com/CS2103-AY1819S2-W17-3/main/pull/88[#88],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/106[#106],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/110[#110])

* Community:
** PRs reviewed: https://github.com/CS2103-AY1819S2-W17-3/main/pull/63[#63],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/64[#64],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/99[#99],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/121[#121]



== Contributions to the User Guide

These are additions I made to _In-Credit-Ble_'s User Guide for the `reverse` and `sort` features.

include::../UserGuide.adoc[tag=sort]

include::../UserGuide.adoc[tag=reverse]

== Contributions to the Developer Guide

These are additions I made to _In-Credit-Ble_'s Developer Guide for the `reverse` and `sort` features.

include::../DeveloperGuide.adoc[tag=sort]

include::../DeveloperGuide.adoc[tag=reverse]
