= Kok Jia Xuan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: In-Credit-Ble

---

== Overview

* rephrase another day *

My team and I were tasked with morphing a basic command line interface addressbook into something else for our Software Engineering project.
We decided to morph it into a finance tracker, and named it In-Credit-Ble. This application allows users
to set budgets and track their spendings through the command line interface.


My role was to design and write the codes for the reverse and sort features.
The following sections explain these enhancements in more detail, and also show the relevant sections
I have added to the user and developer guide in relation to these enhancements.


== Summary of contributions

* rephrase another day *

This section shows a summary of my coding, documentation, and other helpful contributions to the team project.

=== Enhancement added

* rephrase another day, add in -asc and -desc stuff *

I added a reverse and sort feature into the software.

* What they do: +
The `reverse` command allows users to reverse the list of entries displayed on the graphic user interface.
The `sort` command allows users to sort the entries by name or category in alphabetical order,
amount from largest to smallest and date from most recent to least recent
(`sort -name`, `sort -cat`, `sort -amount` and `sort -date` ).

* Justification: +
Without the sort command, entries will be displayed in an order where the most recently entered entry is at the bottom of the list.
However, this may not be very helpful and user-friendly to the user. A user may want to sort the entries by amount,
so that he/she can find out what he/she has been spending the most on.
A user may also want to sort entries by name, date and category to make the list more organised.

The reverse command will allow the user to reverse the list. Since the 4 sort capabilities have a default ordering,
a user may want to view the entries in the opposite way. For example, a user may want the entry with the smallest expense
at the top of the list, or a user  may want the entries to be sorted in a way where the least recent expense is the top.
The user can then execute the `reverse command` after the `sort -amount` command and `sort -date` command respectively.

* Highlights:

-- not doneeee --

This enhancement … +
An in-depth analysis of design alternatives was necessary to … +
The implementation was also challenging as it required changes to existing commands ….

=== Code contributed
Click https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=kjiaxuan[here] to see the code I contributed to the In-Credit-Ble project!


=== Other contributions
* Enhancements:
** Added aliases for the earlier commands and allowed commands entered to be case-insensitive so that the software
becomes more user-friendly and convenient to use. +
(Pull Requests: https://github.com/CS2103-AY1819S2-W17-3/main/pull/15[#15],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/22[#22],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/71[#71])
** Imported DateTimeFormatter and LocalDate into the project to make management of dates easier. +
(Pull Requests: https://github.com/CS2103-AY1819S2-W17-3/main/pull/90[#90])
** Worked on debugging the system tests and increased code coverage. +
(Pull Requests: https://github.com/CS2103-AY1819S2-W17-3/main/pull/177[#177])

* Documentation:
** Updated and formatted parts of User Guide and Developer Guide. +
(Pull Requests: https://github.com/CS2103-AY1819S2-W17-3/main/pull/88[#88],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/106[#106],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/110[#110])

* Community:
** PRs reviewed: https://github.com/CS2103-AY1819S2-W17-3/main/pull/63[#63],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/64[#64],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/99[#99],
https://github.com/CS2103-AY1819S2-W17-3/main/pull/121[#121]



== Contributions to the User Guide
|===
|_These are additions I made to the In-Credit-Ble User Guide for the `reverse` and `sort` features._
|===

include::../UserGuide.adoc[tag=sort]

include::../UserGuide.adoc[tag=reverse]

== Contributions to the Developer Guide
|===
|_These are additions I made to the In-Credit-Ble Developer Guide for the `reverse` and `sort` features._
|===

include::../DeveloperGuide.adoc[tag=sort]

include::../DeveloperGuide.adoc[tag=reverse]
