= Keith Sim - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: TeethHub

---

== Overview

TeethHub is a desktop patient-record application meant for tech-savvy dental practitioners who
prefer interacting with Command-Line Interfaces (CLI) based programs over Graphical User Interface (GUI) based ones.

The user interacts with it using a CLI, and it has a GUI created with JavaFX to display data for the user.
 It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to sort displayed data*
** What it does: allows the user to sort either patient or record data according to their desired parameter and sort
order depending on the mode it's in.
** Justification: A user can have large amounts of data stored within the program. This feature improves the product
significantly by allow the user to view that data in the desired parameter order so that it becomes easier for the
user to locate them.
** Highlights: This feature automatically switches the type of data (patient or record) that it sorts
depending on the mode the program is in. This feature reorders the stored data within the json storage
                file as well.

* *Major enhancement*: added *the ability to find patients and records through all available parameters*
** What it does: allows the user to find a desired patient or record based on the specified parameter(s) and keywords.
The user can additionally choose if they want the search to be case sensitive, and if the search should find data
containing at least one keyword or if the search should find data that contains all keywords.

** Justification: A user can have large amounts of data stored within the program. This feature allows the user
greater refinement over the parameters to find a particular desired patient.
** Highlights: This feature automatically switches the type of data (patient or record) that it searches through
depending on the mode the program is in.

* *Major enhancement*: added *the ability to view a patient's statistics report*
** What it does: allows the user to view a detailed report of the select patient containing their latest teeth, all
linked user information, as well as a breakdown of their associated records.
** Justification: A patient might be a frequent visitor to the user's dental practice, hence the user may want a
detailed report so that they can analyze potential trends.
** Highlights: This feature has three different ways of record data visualization; a simple table; a bar chart, and a
 pie chart.

* *Minor enhancement*: added a Next Of Kin class as an attribute for a patient.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
