= Kyler Wong - Project Portfolio for TeethHub
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== About the Project: TeethHub

TeethHub is a desktop application specially designed for tech-savvy dentists, who prefers to use the command line interface, as opposed to the traditional graphical user interface.

The user interacts with the application through the type via the command line interface, and graphical representations of the stored data will be shown.
The program is written in Java.

== Summary of contributions

* *Major enhancement*: enhanced the *person* storage into a *dental patient* storage
** What it does: This new data structure allows our users to store personal information of patients.
** Justification: This data structure creates the foundation of the product, as TeethHub is an application which manages dental patients for our users.
** Highlights: This enhancements affects existing commands and commands to be added in the future.
The development of patient required an in-depth knowledge of the dentistry industry.
The implementation too was challenging as it required major changes to existing commands.

* *Major enhancement*: added the ability to *store and manage dental records* to patients
** What it does: This allows our users to store dental records on TeethHub, which will be linked to a specified dental patient.
** Justification: This feature is essential to TeethHub as the product wish to offload the workload for dentists, and dental records are the primary documents which dentists handle.
** Highlights: This enhancement affects how data is stored, written and read.
It required a thorough understanding of the design requirements, as well as its constraints.
The implementation too was demanding, as many factors need to be considered.

* *Minor enhancement*: added a goto command that allows the user to navigate to the specified patient's record list from the current patient list.

* *Minor enhancement*: added a back command that allows the user to return back to the patient list from the current record list.

* *Minor enhancement*: added a new user interface which displays the dental record information of a specified patient.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (4 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=patient]

include::../DeveloperGuide.adoc[tag=goto]
