= Chang Lei - Project Portfolio for BrainTrain
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:toc:
:toclevels: 1
:toc-title: Table of contents
:toc-placement: manual
:sectnums:
:repoURL: https://github.com/CS2103-AY1819S2-W14-1/main
:pullURL: https://github.com/CS2103-AY1819S2-W14-1/main/pull/
:seeduURL: https://github.com/se-edu/addressbook-level4

== PROJECT: BrainTrain

This project portfolio page displays my contributions to the BrainTrain project.

== Overview

BrainTrain is an open-source spaced repetition flashcard application for people who need to memorise something which is content heavy. Research has shown that the Spaced-Repetition System (SRS) is much more effective than traditional memorization techniques since it help users review more their poorly memorised words. With BrainTrain, you will learn more with less time since this application makes memorizing an easier and more efficient job.

BrainTrain is also a portable and easy-to-navigate desktop program. It is an offline application which you can use anywhere, even in places with limited or no Internet availability. It can be navigated and used via easy-to-use commands through the Command Line Interface (CLI). The CLI is supplemented by a minimalistic Graphical User Interface (GUI) which provides helpful but non-distracting visual aid. Together, the CLI and GUI provides an effective and straightforward way for you to use BrainTrain.

== Summary of contributions

* *Major enhancement*: Session and session manager model
** *What it does*: Session model generates quiz cards that are needed to be tested in quiz mode based on storage data both from lesson and user progress.
** Justification: To choose the most suitable words for users to learn, session model also has a manager to do the spaced repetition analysis. The method will always generate the cards with the closet due date to users. It can update the user progress after each quiz session as well.
** Highlights:

* *Minor enhancement*: quiz start command

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]

* *Other contributions*:

** Project management:

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide, showing development that I have made for the `start` feature. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=start]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===


