= Chang Lei - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: BrainTrain

This project portfolio page displays my contributions to the BrainTrain project.

== Overview

AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Session and session manager model
** *What it does*: Session model generates quiz cards that are needed to be tested in quiz mode based on storage data both from lesson and user progress.
** Justification: To choose the most suitable words for users to learn, session model also has a manager to do the spaced repetition analysis. The method will always generate the cards with the closet due date to users. It can update the user progress after each quiz session as well.
** Highlights:

* *Minor enhancement*: quiz start command

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]

* *Other contributions*:

** Project management:

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=quiz]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=quiz]
