= Liu Yiyang - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: docX

---

== Overview

docX is a desktop clinic management application designed for receptionists in clinic. It has a GUI but most of user interactions happen using a CLI(Command Line Interface).

== Summary of contributions

* *Major feature*: added *Medical History* and added *adding, listing, editing, sorting, searching and selecting of medical history*
** *Medical History*: Medical History class links Doctor and Patient. The implementation of Medical History and all commands of Medical History allows the receptionists in clinic to record medical histories, which contain information of attending patient, attending doctor, happening date and doctor's description.
** *Add Medical History Command*:
*** Records patient's medical histories of seeing doctors. After a patient seeing a doctor, a medical history of the attending patient and doctor will be created.
*** Added medical history contains all information of the attending patient and doctor.
** *List Medical History Command*:
*** Shows list of all medical histories recorded in docX
*** Shows filtered medical histories list that satisfies user-specified constraints. User can filter medical histories with a specified patient, a specified doctor and a specified date.
** *Edit Medical History Command*:
*** Allows users to edit the write up of medical history.
*** Helps users to manage multiple records of the same patient and doctor on the same day. If a patient come to a doctor more than one times on the same day, receptionists just need to edit the write up of existing medical history instead of creating a new one.
** *Sort Medical History Command*:
*** Sorts medical histories in ascending order or descending order of happening date.
** *Search Medical History Command*:
*** Allows users to find all medical histories related to specified keywords.
** *Select Medical History Command*:
*** Shows details of a specified medical history, including patient's information, doctor's information, date and write up from doctor.

* *Justification of Major Feature*: This feature improves the product significantly because medical history records the very important events happening every day in a clinic. Medical history builds relationships between patients and doctors recorded in docX.
* *Highlights of Major Feature*: Recorded medical histories contains information of patients and doctors, and medical histories are affected by commands of patients and doctors. It's challenging to relate Patient and Doctor class. It's also challenging to always keep medical histories consistent with patients and doctors.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Submitted documents in milestone
** Enhancements to existing features:
*** Updated the GUI to show multiple lists
** Documentation:
*** Update User Guide and Developer Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments):
*** Reported bugs and suggestions for other teams in the class

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
