= Choong Wey Yeh - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Health Hub

Greetings! I am a Year 2 undergraduate in NUS majoring in Computer Science
with a passion for solving real world problems using my technical expertise
in software development and technological knowledge. This portfolio details
the contributions that I have made to HealthHub, the considerations and also
the decisions made in my implementation of various functions in HealthHub.

== Overview

In light of the overwhelming workload of hospital administration teams due
to rising need for more and better healthcare services, we at
team W09-2 have designed and developed a desktop application that aims to
improve the hectic workload of hospital administrative staff by providing a
simple and efficient solution for managing requests for healthcare services
from home-stay patients: *HealthHub*.

HealthHub is a desktop application built in Java and JavaFX that supports
both a Command Line Interface(CLI) and a Graphical User Interface(GUI),
providing the user with the flexbility to choose the mode of use that he or
she prefers.

As a member of the team tasked with the development of HealthHub, my role was
to design the command logic structure for parsing commands and inputs
entered by the user, as well as implementing the logic for commands
involving `HealthWorker` which represents the details of medical experts
register in HealthHub.

== Notation

* Words used that are highlighted in grey represents an existing `Class` or
`Object` that is implemented in HealthHub. E.g `HealthWorker` denotes the
object used to describe the details representing a registered medical expert.

[NOTE]
====
Documentation under this section denotes any additional information used to
supplement existing description.
====

== Contributions

=== Summary of Contributions

Over the course of the development phase, I was tasked with the development
of `HealthWorker` related features in HealthHub, such as the basic Create,
Read, Update and Delete(CRUD) functionality. The enhancements and features
that I have contributed to HealthHub are:

* Creation of the `HealthWorker` representation model for describing a
people working in the medical profession, in HealthHub.
* `add`, `edit` and `delete` commands for registering `HealthWorker` into
HealthHub.
* Designing and implementing the architecture for `CommandParser` to
provide flexibility for the development of other commands, as well as
streamline the performance of user input parsing.
* `filter` command for `HealthWorker` objects, utilizing a combination of
optimized data structures and methods from Java's `Predicate` and `Function`
library.


=== Major Enhancements

* I reworked the `CommandParser` classes in HealthHub to facilitate the parsing
 of inputs for commands involving both `HealthWorker` and `Request` objects.
** The original implementation of `CommandParser` class in AddressBook4 only
facilitated the adding of a `Person` class object into the system. As
HealthHub stored multiple different types of objects such as `HealthWorker`
and `Request`, I had to rework the existing implementation of `CommandParser`
 in AddressBook4 to cater to the needs of our application.
** I created the `CommandMode` class for use in the new release for
`CommandParser` class, and overhauled the implementation to use `CommandMode`
 to identify the specific type of object being handled, as well as to place
 restrictions on unvalidated user inputs during commands. My contribution to
 HealthHub via the `CommandParser` class paved the way for other teammates to
 use the new revised `CommandParser` class for the development of their features
  as well.
** Adjusted the implementation for `FilterCommandParser`, `ListCommandParser`
and `DeleteCommandParser` implemented by my teammates use `CommandMode` to
for a more seamless integration of the `filter`, `list` and `delete` commands
 into HealthHub.

* Added the functionality to filter `HealthWorker` objects in the HealthHub
system using various fields.
** In some of the user stories prior to the development of HealthHub, many
potential users greatly favored the capability to be able to search for
specific types of requests or medical workers, thus speeding up their search.
** To facilitate the ease of finding and assigning `HealthWorker` in HealthHub,
I implemented the ability to filter the existing list of
`HealthWorker`. As a result, Users are able to reduce their search for the
most appropriate health staff for assignment to requests to a shorter list
based on filter conditions they input.
** A significant difficulty that was faced when implementing this feature, is
 the ability to combine multiple conditions of user inputs. The two main
 solutions that were considered were firstly, storing all the filter
 conditions into a `List<Predicate`, while the second solution involved
 condensing all the filter conditions into a single `Predicate` using Java's
 `Predicate` and `Function` library methods. The considerations for each
 solution are as follows:

include::../DeveloperGuide.adoc[tag=filterHealthWorkerTable]

*** Weighing both the pros and cons of both design considerations, I decided to
 go with composing multiple `Predicates` into a single `Predicate` by using
 the functional programming paradigm through Java's `Predicate` and
 `Function` libraries. This is because doing so increases the ease of
 implementation for future enhancements to HealthHub with the increased
 flexibility, and also future implementations are less tightly coupled as
 they only need to depend on `Predicate` and not `List`.

{nbsp}

=== Other Contributions

*Minor Enhancements*:

* Added the ability for users to perform Create, Read, Update and Delete
(CRUD) operations for health workers in HealthHub by implementing the `add
healthworker`, `edit healthworker` and `delete healthworker` commands.
* Wrote incremental integration tests for existing features in HealthHub, as
well as features implemented by my teammates to ensure that the logic and
model components in HealthHub are integrated together smoothly without hiccups.

*Design*:

* Proposed the layout and structure of the implementation of the current
Graphical User Interface(GUI) of HealthHub.

*Project Management*:

* Proposed the architecture design of the current implementation for the
command logic side of HealthHub.
* Delegated features and roles to various team members for their
contributions to HealthHub.

*Documentation*:

* Contributed to the descriptions of each feature by reviewing the
explanation of features in the User Guide, and overhauling it to be more
informative and audience-focused.
* Provided the notation and structure for my team to follow when documenting
our changes and contributions made to HealthHub in the User Guide.

*Community*:

* Reviewed PRs of fellow teammates, and gave suggestions on certain code
snippets
* Contributed to discussions on github pull requests by other team members,
providing suggestions that were eventually adopted in our existing
development releases.

*Tools*:

* Set up the continuous integration plugins TravisCI for the team repository
for HealthHub.
*  Set up auto-publishing of documentation for HealthHub for the team
repository.

== Contributions to the User Guide

As my team and I transformed the original implementation of AddressBook4 to
HealthHub, we have also extensively updated the User Guide to allow for users
 to better understand what HealthHub aims to achieve, and how it does so.

The following sections details my contribution to the User Guide up til
HealthHub version release v1.4.

include::../UserGuide.adoc[tag=filterHealthWorker]

== Contributions to the Developer Guide

To ensure that future developers contributing to HealthHub, as well as users
who wish to improve the implementation and functionality of the
application, my team and I have also published detailed documentation of each
 of the features we have implemented, so that potential contributors can
 easily understand the structure and logic of the features that we have put
 in place.

The following sections details my contribution to the Developer Guide for
HealthHub up til version release v1.4:

include::../DeveloperGuide.adoc[tag=filterHealthWorker]
