= Lim Shao Hong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: GradTrak

---

== Overview

My team was tasked with enhancing a basic command line interface (CLI) AddressBook for our Software Engineering project.
We decided to morph it into a school module tracker called GradTrak. +
GradTrak is an application designed for students of National University of Singapore (NUS) to easily plan and track modules as well as check them against the graduation requirements. +
The user interacts with GradTrak mainly through the CLI, but it also has a Graphical User Interface (GUI) created with JavaFX. It is written in Java and has more than 10 kLoC.

My role was to design and write the codes for the module recommendation feature, and to enhance the existing module finding feature.
The following sections illustrate these contributions in more detail, as well as the relevant sections I have added to the User Guide and Developer Guide.

== Summary of contributions

This section summarises my coding and other helpful contributions to GradTrak.

* *Major enhancement*: added a *module recommendation* feature
** _What it does:_ This feature displays a list of modules which the user is recommended to read based on existing GradTrak modules and graduation requirements specific to the user's course of study.
The list is sorted primarily by the priority of the requirement type satisfied by the recommended module, and secondarily by the level of the module.
** _Justification:_ This feature significantly benefits users who are unfamiliar with the exact graduation requirements of their course, or are unsure of what modules to read for future semesters.
They can simply pick a high-priority module near the top of the recommendation list -- this module already has its prerequisites satisfied, contributes to their graduation requirements and
will likely serve as a prerequisite for higher level modules. This allows users to plan their modules systematically so that they are on the right track towards graduation.
** _Highlights:_

* *Minor enhancement*: added additional parameters for the module finding feature, allowing the user to search GradTrak modules by
module code, semester, grade or finished status.

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=lshwayne96[Project Code Dashboard]]

* *Other contributions*:
-find bugs for other teams
-proofread, polish UG/DG
-helped with course req stuff
-pr review, milestone, user story

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=rec]

include::../UserGuide.adoc[tag=find]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=rec]
