= Lim Shao Hong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: GradTrak

---

== Overview

My team was tasked with enhancing a basic command line interface (CLI) AddressBook for our Software Engineering project.
We decided to morph it into a school module tracker called GradTrak. +
GradTrak is an application designed for students of National University of Singapore (NUS) to easily plan and track modules as well as check them against the graduation requirements. +
The user interacts with GradTrak mainly through the CLI, but it also has a Graphical User Interface (GUI) created with JavaFX. It is written in Java and has more than 10 kLoC.

My role was to design and write the codes for the module recommendation feature, and to enhance the existing module finding feature.
The following sections illustrate these contributions in more detail, as well as the relevant sections I have added to the User Guide and Developer Guide.

== Summary of contributions

This section summarises my coding and other helpful contributions to GradTrak.

* *Major enhancement*: added a *module recommendation* feature
** _What it does:_ This feature displays a list of modules which the user is recommended to read based on existing GradTrak modules and graduation requirements specific to the user's course of study.
The list is sorted primarily by the priority of the requirement type satisfied by the recommended module, and secondarily by the level of the module.
** _Justification:_ This feature significantly benefits users who are unfamiliar with the exact graduation requirements of their course, or are unsure of what modules to read for future semesters.
They can simply pick a high-priority module near the top of the recommendation list -- this module already has its prerequisites satisfied, contributes to their graduation requirements and
will likely serve as a prerequisite for higher level modules. This allows users to plan their modules systematically so that they are on the right track towards graduation.
** _Highlights:_

* *Minor enhancement*: added additional parameters for the module finding feature, allowing the user to search GradTrak modules by
module code, semester, grade or finished status.

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=lshwayne96[Project Code Dashboard]]

* *Other contributions*:

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=rec]

include::../UserGuide.adoc[tag=find]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=rec]
