= Luca Triglia - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ACQUIZITION

---

== Overview

_Acquizition_ is a desktop flashcard application used for language acquisition and training.

Through the use of a Spaced Repetition System, _Acquizition_ maximises user retention
by testing vocabulary most likely to be forgotten by a user.

The application has an intuitive and simplistic interface, making it great for both inexperienced and more proficient computer users.

Developed at the National University of Singapore, _Acquizition_ was created as part of a software engineering team project (module code: CS2103T).
As such, this application was not entirely developed by me. This portfolio serves to
outline my own contributions towards the project.



== Summary of contributions

* *Major enhancement*: added *the ability find specific flashcards*
** What it does: allows the user to find and list flashcards based on specific properties such as front face text,
back face text, tags and success rate.
** Justification: This feature represents the core of the application, as many other commands like the quiz command
depend on the find feature. For instance, if a user wants to be quizzed on chinese, the user must first find the corresponding chinese cards.
** Highlights: This enhancement touches upon multiple components of the project architecture and as a result, was challenging
to implement. Since many other features of the application depend on this functionality, I had to consider many design
implementations to make it as user centric as possible.

** Credits: This feature was enhanced from the existing codebase of the CS2103T project.
** Related code: https://github.com/CS2103-AY1819S2-T12-2/main/pull/29[Enhance Find Command], https://github.com/CS2103-AY1819S2-T12-2/main/pull/85[Find Command - Filter by Success Rate]


* *Major enhancement*: added *the ability share and import flashcards*
** What it does: allows the user to save locally created flashcards to a text file so that they can be distributed and used by other _Acquizition_ users.
** Justification: This application is targeted at language students. As such, this feature would prove beneficial to
users who wish to make use of another persons card collection without needing to manually re-create the flashcards.

** Related code: https://github.com/CS2103-AY1819S2-T12-2/main/pull/12[Add Import Functionality], https://github.com/CS2103-AY1819S2-T12-2/main/pull/43[Add Share Functionality],
https://github.com/CS2103-AY1819S2-T12-2/main/pull/85[Tweak Import and Share Functionality]


* *Other contributions*:

** Project management:
*** Updated AboutUs and ContactUs project pages (Pull request https://github.com/CS2103-AY1819S2-T12-2/main/pull/1[#1])
*** Created Project Portfolio Pages for each team member
** Documentation:
*** Verified the quality of project documentation (User Guide and Developer Guide).
** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/nus-cs2103-AY1819S2/pe-dry-run/issues/719[1],
https://github.com/nus-cs2103-AY1819S2/pe-dry-run/issues/875[2], https://github.com/nus-cs2103-AY1819S2/pe-dry-run/issues/400[3])

A comprehensive summary of all the code contributed can be found https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=lucatriglia[here].

== Contributions to the User Guide


|===
|_Maintaining a comprehensive and coherent User Guide is essential for any Software Engineering project.
Given below are sections I contributed to the User Guide of Acquizition. They showcase my ability to write user-centric documentation._
|===

include::../UserGuide.adoc[tag=find]

include::../UserGuide.adoc[tag=share]

include::../UserGuide.adoc[tag=import]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide of Acquizition. They showcase my ability to write technical documentation
targeted at developers and project managers. They also serve to show the technical depth of my contributions._
|===

include::../DeveloperGuide.adoc[tag=findfeature]

==== Use case: Find cards
include::../DeveloperGuide.adoc[tag=findfeatureMSS]

include::../DeveloperGuide.adoc[tag=share_import]

==== Use case: Share a collection of cards
include::../DeveloperGuide.adoc[tag=sharefeatureMSS]

==== Use case: Import a collection of cards
include::../DeveloperGuide.adoc[tag=importfeatureMSS]


