= Minern Chan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview

Club Manager is a desktop CCA management application used for managing CCA members. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Helped in creation of the activity list functionalities and added the ability to place members in the attendance lists of activities.
** What it does: Allow users to store records of the Club activities, and keep track of members who are attending/attended particular activities.
** Justification: This feature improves the product significantly because instead of looking at two separate lists without any meaning, there is now a relation between the members and activities (who is attending which activity).
** Highlights: This enhancement affects existing commands and commands to be added in the future. Our team spent a considerable amount of time planning the design of the Activity Class, and how it should interact with the Member object. The implementation was tedious as it required a lot of new commands and functions, in addition to the editing of existing functions.
** Credits: [https://github.com/nus-cs2103-AY1819S2/addressbook-level4[Existing AddressBook-Level4 code]]

* *Minor enhancement*: Implemented the ActivityDeleteCommand, to permanently remove records of an existing activity from the database.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:

** Enhancements to existing features:

** Documentation:

** Community:

** Tools:

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=activityDelete]

include::../UserGuide.adoc[tag=activityAddMember]

include::../UserGuide.adoc[tag=activityDeleteMember]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=activityDelete]

include::../DeveloperGuide.adoc[tag=activityAddMember]

include::../DeveloperGuide.adoc[tag=activityDeleteMember]

== PROJECT:

---

_{Optionally, you may include other projects in your portfolio.}_
