= Lee Yi Quan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: GradTrak - A Graduation Tracker for NUS

---

== Overview

GradTrak is an application that was morphed from the codebase of https://github.com/nus-cs2103-AY1819S2/addressbook-level4[Address Book - Level 4].
It was conceptualised and designed in mind to assist students of NUS to track their graduation progress and plan future modules that they want to take.

== Summary of contributions

* *Major feature*: added the functionality for users to track their graduation requirements
** What it does: allows the user to check against the a list of modules they have taken / are planning to take, whether
they have fulfilled the requirements. If the requirement is not fulfilled, the feature also allows the users
to know approximately, the extent of completion of these graduation requirements and suggest the suitable modules
they can take to satisfy the requirement

** Why this feature: This feature is one of the core functionalities of GradTrak. This greatly enhances quality of life of
students in NUS as it would allow them to find out the modules they can take to satisfy graduation requirement.

** Highlights: It is difficult to implement this feature properly because it is difficult to capture the
key characteristics of graduation requirements since they can vary quite a fair bit.
I had to do some research on design patterns to understand how to mimic
some of the behaviours of Course Requirements as intended.

* *Minor enhancement*: created user editable files for users to store different courses
and course requirements, added some sample courses into the application namely: Computer Science Algorithms, Artificial Intelligence
and Software Engineering.

* *Code contributed*: [https://github.com/cs2103-ay1819s2-w14-4/main/tree/master/src/main/java/seedu/address/model/course[Functional code]] [https://github.com[Test code]]

* *Other contributions*:
** Project Management
*** Set up milestones, issue tracker
*** Put up user stories

** Refactored Code
*** Renamed significant amount of variables, classes in Address Book - Level 4 code base
*** Updated some documentation and their visuals inherited from Address Book - Level 4 to match GradTrak

** Documentation:
*** Changed some visuals for the User Guide, Developer Guide https://github.com/cs2103-ay1819s2-w14-4/main/pull/90[#90]
*** Changed some of the prose of the User Guide, Developer Guide (see above PR)
*** Modified some sections of User Guide, Developer Guide


== Contributions to the User Guide

include::../UserGuide.adoc[tag=Displayreq]

include::../UserGuide.adoc[tag=study]

== Contributions to the Developer Guide

include::../DeveloperGuide.adoc[tag=CourseRequirement]


== PROJECT: Cuckoo Hash
An experimental assignment from https://www.comp.nus.edu.sg/~gilbert/CS5330/[CS5330 - Randomised Algorithm]
to investigate various effects of different Cuckoo Hash schemes.
https://www.comp.nus.edu.sg/~gilbert/CS5330/2019/psets/ExperimentalAlgorithms.pdf[More information on assignment here]
and https://github.com/monikernemo/CS5330-Experimental-Assignment[more on the codes of the implementation here]