= Ong Yi Chong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Know-It-All

---

== Overview
My team and I were tasked with enhancing a basic command line interface addressbook for our
Software Engineering project. We chose to morph it into an desktop flashcard application
called Know-It-All. This enhanced application helps students organize their digital flashcards neatly.
The application also comes with a test feature; allowing users to test themselves on the flashcards
created, a report feature; allowing them to view their performance for each folder and a import and
export feature; which allows for the sharing of flashcards.

My role was to design and write the codes for the import and export features. The following sections
illustrate these enhancements in more detail, as well as the relevant sections I have added to the
user and developer guides in relation to these enhancements.


== Summary of contributions

* *Major enhancement*: added *the ability to import/export existing or new flashcards*
** What it does: The import and export command allows users to import and export flashcards as csv files.
** Justification: This feature improves the product significantly because users can now share their flashcards with
others. The ability to import flashcards also provides a faster alternative to creating multiple flashcards in comparison
to manually adding within the app iteself.
** Highlights: Although not technically challenging, there were many considerations that went into the design of the import/export feature. One of them was deciding
the formatting of csv files. whether a user should be able to export multiple card folders into a single csv. Also, since commas
were used within each card field as well, there was a need to ensure that the comma separated values are actually not
part of the "commas" within the card field itself.


** Credits:


* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=yichong96[Collated code]]

* *Other contributions*:
** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage from 78.379% to 81.079 (Pull requests https://github.com[#105])
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/cs2103-ay1819s2-w10-4/main/pull/60[#60], https://github.com/cs2103-ay1819s2-w10-4/main/pull/2[#2]



== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag = advancedoperations]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=importexport]
