= Ong Si Ying - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: docX

This portfolio aims to document my contribution to the project *__docX__*.

Github: https://github.com/cs2103-ay1819s2-w13-1/main

== Overview

docX is a desktop clinic data management application used to maintain clinic's database. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added the ability to *find relevant and available doctors based on specialisation and the desired date and time*
** What it does: Allows the user to find doctors whose specialisation matches the input and are available at the desired date and time for an appointment.
** Justification: This feature improves the product significantly because the user can now find available doctor(s) that match(es) the required specialisation with just one command, instead of the traditional method, where the user has to scroll through the list of doctors to find them manually.
** Highlights: This enhancement required an in-depth analysis of design alternatives. The implementation too was challenging as it required access to another class' information (Appointment list under ModelManager) and temporary changes made to the Appointment Filtered List under Model Manager during implementation.

* *Minor enhancement*: making searching of doctors by keywords more convenient with the usage of just 1 command.
** What it does: Allows the user to find doctors whose fields matches the keyword(s) inputted.
** Justification: This feature allows the user to intuitively use the same command word for different functions. `list-d` now can be used to list the full original list of doctors and `list-d 10` will list doctors whose field(s) contains '10'. Hence, the user just needs to remember 1 command word for listing and searching of the doctors.
** Highlights: This enhancement although minor, proved to be a challenge because the parser for this command has to accept any number of keywords (0 to infinitely many). Hence, the parser must be prepared to take in null arguments and many arguments too.

* *Code contributed*: Find my code contributed https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=siyingpoof[here].

* *Other contributions*:

** Enhancements to existing features:
*** Allowing the display of doctors' information on the browser panel. (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage by 8%. (Pull requests https://github.com/cs2103-ay1819s2-w13-1/main/pull/198[#198], https://github.com/cs2103-ay1819s2-w13-1/main/pull/202[#202], https://github.com/cs2103-ay1819s2-w13-1/main/pull/205[#205])
** Community:
As of 15 April 2019,

*** https://github.com/cs2103-ay1819s2-w13-1/main/pulls?q=is%3Apr+is%3Aclosed+author%3Asiyingpoof)[Pull Requests (PRs)] on *__docX__*'s GitHub = 25
*** https://github.com/cs2103-ay1819s2-w13-1/main/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Asiyingpoof[PRs reviewed] with non-trivial review comments = 3 (https://github.com/cs2103-ay1819s2-w13-1/main/pull/212[#212], https://github.com/cs2103-ay1819s2-w13-1/main/pull/113[#113], https://github.com/cs2103-ay1819s2-w13-1/main/pull/93[#93])
*** https://github.com/cs2103-ay1819s2-w13-1/main/issues?q=is%3Aissue+is%3Aclosed+author%3Asiyingpoof[Issues] raised on *__docX__*'s GitHub = 5
*** https://github.com/nus-cs2103-AY1819S2/pe-dry-run/issues/created_by/siyingpoof[Reported bugs and suggestions] for other teams in the class (examples: https://github.com/nus-cs2103-AY1819S2/pe-dry-run/issues/311[1], https://github.com/nus-cs2103-AY1819S2/pe-dry-run/issues/809[2],  https://github.com/nus-cs2103-AY1819S2/pe-dry-run/issues/265[3])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=doctorcommands]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=doctorcommands]
