= Koh Wei Xin - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: FoodDiary

---

== Overview

This project portfolio page documents my contributions to *_The Food Diary_*, a software engineering project undertaken as part of the Software Engineering module, CS2103T, during my undergraduate studies in the National University of Singapore (NUS).
This application is written in Java and has about 10,000 lines of code. It utilizes Command Line Interface (CLI) and has a Graphical User Interface (GUI) created using JavaFX.

*_The Food Diary_* is a desktop application morphed from a basic CLI AddressBook.
Through our *Software Engineering* module, CS2103T, my team and I chose to morph the AddressBook into a The Food Diary for food lovers of all ages to document their very own food adventure.

The main features of *_The Food Diary_* include:

* Adding, editing and deleting restaurants
* Adding, editing and deleting reviews
* Getting aggregate ratings for restaurants based on personal reviews
* Get recommendations to new restaurants nearby

*_The Food Diary_* supports both Windows and Mac operating systems.

== Summary of Contributions

The following are the contributions I made to this project, in the form of enhancements, code contributions, project management, documentation and community.

* *Major Enhancement*: I added the ability to *generate and display aggregate restaurant data*.
** *What it does*: Generates aggregate rating from all the reviews of a restaurant and display it in the restaurant card as well as in a summary panel for the restaurant.
** *Justification*: This feature improves the product significantly because a user can now immediately see his/her personal ratings across all the visits they made for a restaurant.
** *Highlights*: This enhancement required in-depth analysis of other alternatives. Additionally, it relied heavily on XML-based user interface markup language, FXML. Thus, I had to learn pick up this language from scratch to display this new `UiPart`.
The implementation was also challenging as it involved multiple components, namely `Model`, `Logic` and `Ui`, for it to work.
** *Code Contributed*:
*** Functional Code:
https://github.com/CS2103-AY1819S2-W17-1/main/pull/103[#103]
*** Test Code:

* *Minor Enhancement*: I set up the `Review` class and added the ability to display all of the reviews belonging to a restaurant.
** *Code Contributed*:
*** Functional Code:
https://github.com/CS2103-AY1819S2-W17-1/main/pull/25[#25],
https://github.com/CS2103-AY1819S2-W17-1/main/pull/36[#36],
https://github.com/CS2103-AY1819S2-W17-1/main/pull/74[#74],
https://github.com/CS2103-AY1819S2-W17-1/main/pull/89[#89]
*** Test Code:
https://github.com/CS2103-AY1819S2-W17-1/main/pull/36[#36],
https://github.com/CS2103-AY1819S2-W17-1/main/pull/94[#94]

* *Other Contributions*:

** *Project Management*:
*** Recorded all of the user stories as issues. (https://github.com/CS2103-AY1819S2-W17-1/main/issues?q=is%3Aissue+author%3Aweixin-koh+label%3Atype.Story[Issues])
** *Enhancements to Existing Features*:
*** Enabled `Select` command to display not only browser for restaurant, but also the list of reviews and summary for the restaurant. (https://github.com/CS2103-AY1819S2-W17-1/main/pull/74[#74])
*** Changed logo and title of the application to *_The Food Diary_*. (https://github.com/CS2103-AY1819S2-W17-1/main/pull/74[#74])
** *Documentation*:
*** Did cosmetic tweaks to existing contents of the User Guide and Developer Guide (https://github.com/CS2103-AY1819S2-W17-1/main/pull/83[#83], https://github.com/CS2103-AY1819S2-W17-1/main/pull/77[#77])
*** Updated pictures of the UI (https://github.com/CS2103-AY1819S2-W17-1/main/pull/6[#6], https://github.com/CS2103-AY1819S2-W17-1/main/pull/77[#77])
** *Community*:
*** PRs reviewed (with non-trivial review comments) (https://github.com/CS2103-AY1819S2-W17-1/main/pull/2[#2], https://github.com/CS2103-AY1819S2-W17-1/main/pull/95[#95])
*** Reported bugs and suggestions for other teams in the class (*TBC*)
*** Always ensured that at least one teammate has reviewed and approved my PR before merging.
** *Tools*:
*** Setup Reposense (https://github.com/CS2103-AY1819S2-W17-1/main/pull/83[#83])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=select]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=sharereviews]

include::../DeveloperGuide.adoc[tag=selection]
