= Phua Yue Jun - Project Portfolio
:site-section: AboutUs
:icons: font
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: RestOrRant

---

== Overview

RestOrRant is a command line interface (CLI) restaurant management application that my team and I designed for the CS2103T Software Engineering module in NUS School of Computing.
For our module project, we morphed RestOrRant from an address book application into one that allows restaurant managers and waiters to perform front-end operations efficiently.
This includes allocating tables to customers, handling orders, tracking item availability and calculating bills. Managers can also view revenue and order statistics to determine how the restaurant is faring.

We split the application into four main features: Tables, Orders, Menu and Statistics. Each team member was in charge of one feature and mine was the Orders feature.
I also conceptualised and implemented the Mode system alongside my team members.

I will be sharing more about the Orders and Modes features in the following sections, as well as extracting the relevant parts of the User Guide and Developer Guide that I wrote for these features.

You may refer to the table below for the symbols and formatting used in this portfolio.

[width="70%",cols="^15%,85%"]
|===
a| `code` | A grey highlight with monospaced font indicates a command that can be typed into the command box of the application.
a| icon:info-circle[role="icon-note", size="2x"] | A blue information symbol indicates additional information for that section that is good to know.
|===


== Summary of contributions

|===
| In this section, I will provide a summary of the contributions that I have made to the team project. These contributions include the features that I implemented, as well as other project-related contributions.
|===

* *Major enhancement added (Orders feature)*: I added the Orders feature and all of its related commands.
** What it does: It allows restaurant front-end staff to take orders from customers using the `addToOrder` command, as well as remove incorrectly inputted orders using the `deleteFromOrder` or `clearOrder` commands. They can track the current list of items ordered for each table (in Table Mode) or across all tables (in Restaurant Mode) and update their serving statuses with the `serve` command.
** Justification: Restaurant front-end staff will need this core feature as keeping track of orders is one of the crucial front-end operations that restaurants have to manage. This feature allow orders to be handled more efficiently so that customers can be promptly attended to and served.
** Highlights: -

* *Other enhancement added (Modes feature)*: I conceptualised the Mode system and added features related to the changing of modes.
** What it does: RestOrRant has four modes for each of the four features. Users can switch between modes to use the other features by using commands, such as the `restaurantMode` and `tableMode` commands that I implemented.
** Justification: Translating our main features into different application modes provides a functional and visual distinction between the features and makes RestOrRant more organised and clear for its users. The Mode system also allows us to provide users with only the relevant displays for each feature instead of overwhelming users with all the information at one shot.
** Highlights: -

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=whyjayxp[Project Code Dashboard]]

* *Other contributions*:

** Project management:
*** Charted the direction and progress of the project and facilitated weekly project meetings as the team lead
*** Set up the issues tracker on GitHub for our project
*** Managed the integration of code by ensuring the compatibility of merged Pull Requests
** Enhancements to existing features:
*** Updated the GUI colour scheme and implemented the ability to switch between colour schemes for the different modes
*** Wrote additional tests for existing features
** Documentation:
*** Did tweaks to existing contents of the User Guide
**** Reorganised and rewrote the Introduction and Quick Start section
**** Split commands into their respective modes to present a clearer structure
**** Revamped Command Summary into table form for ease of reference
** Community:
*** PRs reviewed (with non-trivial review comments)
** Tools:
*** Set up GitHub, Travis, AppVeyor and Coveralls for our project
*** Set up auto-publishing of docs

== Contributions to the User Guide

|===
| This section shows the additions that I have made to the User Guide to provide information about how the Modes and Orders features work.
|===

include::../UserGuide.adoc[tag=changemode]

include::../UserGuide.adoc[tag=tablemode]

== Contributions to the Developer Guide

|===
| This section shows the additions that I have made to the Developer Guide to show the implementation and design considerations for the Modes feature.
As the implementation for the Orders feature is similar to the basic add, delete and clear commands across the features, I have left the explanation to the other team members to avoid repetition.
|===

include::../DeveloperGuide.adoc[tag=changemode]
