= Lee Wei Kang - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview

This project portfolio page serves to document my contributions to The Food Diary, a software engineering project that was undertaken as part of the National University of Singapore (NUS) School of Computing’s Software Engineering module.

The Food Diary is designed for food lovers whose wish to document their experiences at a restaurants in a fast and simple fashion.
It serves as a journal, allowing the users to give reviews and ratings to the restaurant that they have been to.

My role in this project is to implement a function that allows food lovers to visit the website of restaurants so that they
can reference the website while writing a review.


== Summary of contributions

* *Major enhancement*: added *the ability to visit website of restaurants*
** What it does: allows users to view website of visited and unvisited restaurants.
** Justification:
*** This feature allows users to reference restaurant's website while writing a review for the restaurant.
*** Also, users can search up for restaurants website in the application so that they can fill in details such as their opening hours and price range when adding the restaurant to their list.
** Highlights: This feature requires understanding of java.net library and also handling tricky errors that can arise when connecting to the internet to load websites.
** Credits: Used java.net package to validate websites before allowing users to add them into restaurant class.

* *Minor enhancement*: Enhance add and edit function to validate weblink before adding restaurant into Food Diary.

* *Code contributed*: Here's a https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=wklee96&sort=displayName&since=2019-02-10&until=2019-04-04&timeframe=day&reverse=false&repoSort=true[link] to my code on the Project Code Dashboard.
** Project management:
*** Set-up GitHub organisation to fork Address Book 4
*** Create a dummy GitHub account perform Continuous Integration for our project.
*** Managed release of v1.2
** Enhancements to existing features:
*** Added Opening Hour class and Weblink class as new parameters for Restaurant https://github.com/CS2103-AY1819S2-W17-1/main/pull/29[#29], https://github.com/CS2103-AY1819S2-W17-1/main/pull/17[#17]
*** AddCommand prevents users to enter invalid Weblink that may
*** Updated sample data https://github.com/CS2103-AY1819S2-W17-1/main/pull/17[#17]
** Documentation:
*** Updated README https://github.com/CS2103-AY1819S2-W17-1/main/pull/7[#7]
** Community:
*** Actively looked through and approved PRs, providing constructive comments to codes https://github.com/CS2103-AY1819S2-W17-1/main/pull/103[#103], https://github.com/CS2103-AY1819S2-W17-1/main/pull/95[#95]
*** Raised issues in issue tracker
** Tools:
*** Enabled auto-publishing of documentation for our project


== Contributions to the User Guide


|===
|_The user guide acts as a instruction manual for new users. For my part, I have implemented the visitWeb command feature and below shows an excerpt of Food Diary's User Guide that I added, which explains the usage of visitWeb._
|===

include::../UserGuide.adoc[tag=visitweb]

== Contributions to the Developer Guide

|===
|_The following shows my addition to the developer guide for visitWeb feature._
|===

include::../DeveloperGuide.adoc[tag=visitweb]
