= John Doe - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Equipment Manager

---

== Overview

Equipment Manager is a desktop equipment information management system used for technicians and engineers who need to do maintainance or manage equipments. The user interacts with it using mainly a CLI (command line interface). It also has a GUI (graphical user interface) to serve as secondary approach for users to interact with the application, aslo as the primary approach to display information. The GUI is build with JavaFX, and the whole application is mainly build with Java, except for the static pages to display equipment details and maps.

This project is morphed from link:https://github.com/nus-cs2103-AY1819S2/addressbook-level4[AddressBook-Level4].

== Summary of contributions

* *Major enhancement*: added *the map display feature*
** What it does: allows the user to view equipments or one specific equipment on the map displayed on the right hand side of the application window.
** Justification: This feature is one of the major selling points of this project. The map make this application unique from ordinary information management tools like Excel, which cannot visualize information like address.
** Highlights: The implementation of this feature involes in many technical decisions, including choosing the way to display map (built in or browser), choosing the map JavaScript library, choosing the message passing approach, choosing the way to host static pages and etc.
** Credits: The map templete is taken from link:https://developers.google.com/maps/documentation/javascript/tutorial[Google Maps JavaScript API].

* *Other contributions*:

** Project management:
*** Managed releases `v1.2` on GitHub. (link:https://github.com/CS2103-AY1819S2-W10-3/main/releases/tag/1.2[Releases v1.2])
** Documentation:
*** Remove header of original project for project website: https://github.com/CS2103-AY1819S2-W10-3/main/pull/48[#48]
** Community:
*** PRs reviewed: https://github.com/CS2103-AY1819S2-W10-3/main/pull/39[#39], https://github.com/CS2103-AY1819S2-W10-3/main/pull/94[#94], https://github.com/CS2103-AY1819S2-W10-3/main/pull/99[#99]
*** Reported bugs and suggestions for teammates (examples:  https://github.com/CS2103-AY1819S2-W10-3/main/pull/39[#39])
** Tools:
*** Modify the Gradle automation script to auto publish the static pages into gh-pages branch. (https://github.com/CS2103-AY1819S2-W10-3/main/pull/45[#45])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=select]

include::../UserGuide.adoc[tag=display]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=display]


== PROJECT: Equipment Manager

---


