= Prithivi Raj - Portfolio
Prithivi Raj <www.github.com/ptvrajsk>

== Introduction

This document provides a detailed description to my contributions to
the several projects that I have been a part of over the years. +
My contributions will be substantiated with relevant technical application
and sources, if possible.

== PROJECT: PDF++

PDF++ is an application built on Java that acts as a document management system
that provides some advanced features that improves the quality of life of its
users. +
The application has a working Graphical User Interface (GUI), built upon the
JavaFX framework, that is supplemented with a Command Line Interface (CLI)
to accept more specific requests by the User. +
Although not built to its final form, it boasts a large feature set such as:

- Adding, Moving and Deleting Documents.
- Assigning Custom Tags to Documents.
- Filtering Documents by Custom Tags.
- Assigning Deadlines to Documents that provide a Visual Response to the User.
- Permanent Encryption and Decryption of Documents such that they require
set passwords to open even if accessed outside the application.
- Merging multiple documents into a single document.
