= ClubManager - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/cs2103-ay1819s2-w13-2/main

By: `Team W13-2 2019`      Licence: `MIT`

== Introduction

ClubManager is for those who *prefer to use a desktop app for managing contacts*. More importantly, ClubManager is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI). If you can type fast, ClubManager can get your contact management tasks done faster than traditional GUI apps. Interested? Jump to the <<Quick Start>> to get started. Enjoy!

== Quick Start

.  Ensure you have Java version `9` or later installed in your Computer.
.  Download the latest `clubmanager.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your ClubManager.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`list`* : lists all contacts
* **`add`**`n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01` : adds a contact named `John Doe` to ClubManager.
* **`delete`**`3` : deletes the 3rd member shown in the current list
* *`exit`* : exits the app

.  Refer to <<Features>> for details of each command.

[[User Interface Walkthrough]]
== User Interface Walkthrough

[[Features]]
== Features
This section provides a list of features that are designed to facilitate CCA main committees in the area of member management. 

As a CCA leader, you would be able to:
*View the list of members
*Add/Delete/Edit/Sort/Clear the list of members
*Enter information of members
*Manage the list of activities
*Manage payments
*Import/export member details from/to spreadsheets files
*View and generate reports and statistics
====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.

*Members Management*
ClubManager, at its core, is a member management system that allows you to manage your CCA members’ record more effectively and efficiently.
The following are the list of commands:
====

=== Adding a member: `addmember`

You can add members to ClubManager. +
Format: `addmember n/NAME an/ADMIN_NUMBER p/PHONE_NUMBER e/EMAIL yos/YEAR_OF_STUDY m/MAJOR [t/TAG]...`
****
* YEAR_OF_STUDY refers to the academic level (in years) in which the member is currently studying in YYYY format.
* MAJOR refers to the field of discipline in which member is currently enrolled in.
****
[TIP]
A member can have any number of tags (including 0)

Examples:

* `addmember n/James Ong an/A0123456Y p/98765432 e/jamesong@example.com yos/year1 m/mathematics
* `addmember n/Betsy Crowe an/A0123456Y p/98765432 e/jamesong@example.com yos/year4 m/chemistry t/maincomm

=== Listing all members : `list`

Shows a list of all members in ClubManager. +
Format: `list`

=== Editing a member : `editmember`

Edits an existing member in ClubManager. +
Format: `edit INDEX n/NAME an/ADMIN_NUMBER p/PHONE_NUMBER e/EMAIL yos/YEAR_OF_STUDY m/MAJOR [t/TAG]`

****
* Edits the member at the specified `INDEX`. The index refers to the index number shown in the displayed member list. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* You can remove all the member's tags by typing `t/` without specifying any tags after it.
****

Examples:

* `editmember 1 p/91234567 e/johndoe@example.com` +
Edits the phone number and email address of the 1st member to be `91234567` and `johndoe@example.com` respectively.

* `editmember 2 n/Betsy Crower t/` +
Edits the name of the 2nd member to be `Betsy Crower` and clears all existing tags.

=== Locating members by name: `findmember`

Finds members whose names contain any of the given keywords. +
Format: `findmember KEYWORD [MORE_KEYWORDS]`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* members matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****

Examples:

* `findmember John` +
Returns `john` and `John Doe`
* `findmember Betsy Tim John` +
Returns any member having names `Betsy`, `Tim`, or `John`

=== Deleting a member : `deletemember`

Deletes the specified member from ClubManager. +
Format: `deletemember INDEX`

****
* Deletes the member at the specified `INDEX`.
* The index refers to the index number shown in the displayed member list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `list` +
`deletemember 2` +
Deletes the 2nd member in ClubManager.
* `find Betsy` +
`deletemember 1` +
Deletes the 1st member in the results of the `find` command.

=== Sort members’ list : `sortmembers`

Sort the members list by a member’s attribute in ascending order
Format: n/NAME an/ADMIN_NUMBER p/PHONE_NUMBER e/EMAIL yos/YEAR_OF_STUDY m/MAJOR`

****
* Sorts the member at the specified attribute. The attribute refers to the name, admin number, phone number, email, year of study, and major. There can only be a single attribute provided.
* At least one of the attributes are provided.
* Members will be sorted in ascending order based on the attribute. 
****

Example:

*’list ’ + 
‘sortmembers NAME’
Sorts the list by name. 

=== Clearing all entries : `clear`

You can clears all entries from the members’ list.
Format: ‘clear’

=== Viewing help : `help`
Displays a list of commands and the help messages to guide the user.
Format: `help`

=== Creating an activity: `new activity`
Creates a new activity and adds it to the activity list
Format `new activity [n/ACTIVITY_NAME] [d/DATE] [f/FEES_PER_ATTENDEE] [t/TAG] … `
 
****
* Date refers to the date when the event is occuring in DDMMYYYY format
* Fees refer to the amount payable for each person attending the event
* Activity can be tagged with any amount of tags.
****
 
Examples:
* `new activity n/Annual Welcome Tea d/12022019 f/10 t/casual t/indoor`
* `new activity n/Sentosa Outing d/21032019 f/25 t/outdoor`
 
 
=== Editing an activity: `edit activity`
Edits an existing activity in the activity list
Format: `edit activity ACTIVITY_INDEX [n/ACTIVITY_NAME] [d/DATE] [f/FEES_PER_ATTENDEE] [t/TAG] … `
 
****
* Edits the activity at the specified `ACTIVITY_INDEX` which refers to the index number shown in the displayed activity list.
* The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the activity will be removed i.e adding of tags is not cumulative.
* You can remove all the activity’s tags by typing `t/` without specifying any tags after it.
 
****
Examples:
 
* `edit 1 d/13022019 f/5 ` +
Edits the date and fees of the first activity to be 13 Feb 2019 and $5 respectively.
* `edit 2 f/30 t/` +
Edits the fees of the 2nd activity to be `$30` and clears all existing tags.
 
 
=== Delete an activity `delete activity`
Deletes an existing activity in the activity list
Format: `delete activity ACTIVITY_INDEX `
 
****
* Deletes the activity at the specified `ACTIVITY_INDEX` which refers to the index number shown in the displayed activity list.
* The index *must be a positive integer* 1, 2, 3, ...
****
 
Examples:
 
* `delete 1` +
Deletes the first activity in the displayed activity list
 
=== Add a member to activity `activity add member`
Adds an existing member to an existing activity to indicate that they will be going for the activity.
Format: `activity add member ACTIVITY_INDEX MATRIC_NO`
 
****
* Adds a member to the activity at the specified `ACTIVITY_INDEX` which refers to the index number shown in the displayed activity list.
* The index *must be a positive integer* 1, 2, 3, ...
* MATRIC_NO must be a currently existing entry in any existing member’s MATRIC_NO information column in the member list.
****
Examples:
 
* `activity add member 1 A1234567N` +
Adds the member with matric number `A1234567N` to the attending list for activity 1.
 
=== Delete a member from activity `activity delete member`
Removes an existing member who has already indicated that he/she will be attending the activity from the attending list of the activity.
Format: `activity delete member ACTIVITY_INDEX MATRIC_NO`
 
****
* Removes a member from the attending list of the activity at the specified `ACTIVITY_INDEX` which refers to the index number shown in the displayed activity list.
* The index *must be a positive integer* 1, 2, 3, ...
* MATRIC_NO must be a currently existing entry in the specified activity’s attending list.
****
Examples:
 
* `activity delete member 1 A1234567N` +
Removes the member with matric number A1234567N from activity 1’s attending list.
 
=== List all activities `list activity`
Displays a list of all activities within the activity list.
Format: `list activity`
 
=== Sort all activities by date `sort activity`
Sorts all activities in the activity list according to the event date.
Format: `sort activity`



=== Import member data from local spreadsheet file: `importMembers`
Add members from spreadsheet file
Format: `importMembers FILE_PATH`
 
****
* Import members data from spreadsheet file at location `FILE_PATH` which refers to the path of the spreadsheet file including the filename.
* The path *must be a valid file path to the programme location* as defined in the user’s Operating System.
* The import function parses the data row by row.
* For each row, the programme would attempt to add each member entry as a unique entry to ClubManager.
* On successful addition, the row will be removed from the file.
* If the data in the row does can not be parsed successfully by the programme it will be skipped.
****
 
Examples:
 
* `importMembers ./memberDetails.csv` +
Import members data from memberDetails.csv file and adds them to ClubManager

=== Export currently listed member data to a local spreadsheet file: `exportMembers`
Creates a spreadsheet file containing the member details
Format: `exportMembers FILE_PATH`
 
****
* Export listed members data from spreadsheet file at location `FILE_PATH` which refers to the path of the spreadsheet file including the filename.
* The path *must be a valid file path to the programme location* as defined in the user’s Operating System.
* Each member entry is stored in seperate rows in the file.
****
 
Examples:
 
* `exportMembers ./memberList.csv` +
Exports members data to memberList.csv

=== Export currently listed member data to a local vCard (.vcard) format: `exportVcf`
Creates a spreadsheet file containing the member details
Format: `exportVcf FILE_PATH`
 
****
* Export listed members data from spreadsheet file at location `FILE_PATH` which refers to the path of the spreadsheet file including the filename.
* The path *must be a valid file path to the programme location* as defined in the user’s Operating System.
* Each member entry is stored in seperate rows in the file.
**** 

Examples:
 
* `exportVcf ./members.vcard` +
Exports listed member data to members.vcard

=== Creating payment request : `payments request`

Makes a new payment request. +
Format: `payments request d/DATE a/AMOUNT t/TAG [t/MORE_TAGS]...`

****
*Adds a payment request to the pending payments list
*DATE *must be in DDMMYY format* and be present date
*AMOUNT *must be in .2f format*
*if more than one entry for NAME exists, all members with NAME will be listed and INDEX must be entered to select member
*TAG and MORE_TAGS should specify the purpose of the payment
****

Examples:
* `payments request d/010203 a/888.88 n/John Doe t/club fee t/Feb2003` +
Appends a payment request to pending payments list with above details
*for members John Doe and John Tan 
`payments request d/010203 a/888.88 n/John t/club fee t/Feb2003` +
Returns ‘John Doe, John Tan’
`2` +
Appends a payment request to pending payments list with above details for John Tan

=== Listing pending payments: `payments pending`

Lists all pending payments and their details. +
Format: `payments pending [t/TAG]...`

****
*if TAG is entered, only pending payments with TAG are listed in chronological order
*else all entries are listed by date
****

Examples:
*`payments pending` +
Returns ‘010203 888.88 John Doe club fee Feb2003\n010203 888.88 John Tan club fee Feb2003’
*`payments pending t\club fee`
Returns ‘010203 888.88 John Doe club fee Feb2003\n010203 888.88 John Tan club fee Feb2003’
*`payments pending t\Mar2003`
Returns ‘No pending payments.’

=== Receive pending payments: `payments receive`

Resolve pending payment, remove from pending payments list and add to front of completed payments list. +
Format: `payments receive cd/CURRENT_DATE d/DATE a/AMOUNT n/NAME t/TAG [t/TAG]... `

****
*CURRENT_DATE *must be in DDMMYY format*
*matches all entered fields except CURRENT_DATE with payments pending list
*if one match is found, that entry is removed from pending payments list, and entry with CURRENT_DATE is added to the completed payments list with most recent on top
*else if more than one match is found, all matched entries are listed and INDEX must be entered to select one entry
****

Examples:
*`payments receive cd/290203 d/010203 a/888.88 n/John Doe t/club fee t/Feb2003 `+
Entry is removed from pending payments list, ‘290203 010203 888.88 John Doe club fee Feb2003’ is added to front of completed payments list
*`payments receive cd/010303 d/010203 a/888.88 n/John Tan t/club fee` +
Entry is removed from pending payments list, ‘010303 010203 888.88 John Tan club fee Feb2003’ is added to front of completed payments list
*`payments receive cd/010303 d/010203 a/888.88 n/John t/Feb2003` +
Returns ‘010203 888.88 John Doe club fee Feb2003\n010203 888.88 John Tan club fee Feb2003’
`2` +
John Tan entry is removed from pending payments list, ‘010303 010203 888.88 John Tan club fee Feb2003’ is added to front of completed payments list

=== Listing completed payments: `payments completed`

Lists all completed payments from most recent onwards. +
Format: `payments completed [t/TAG]...`

****
*if TAG is entered, only completed payments with TAG are listed in reverse chronological order
*else all entries are listed in reverse chronological order
****

Examples:
*`payments completed` +
Returns ‘010303 010203 888.88 John Tan club fee Feb2003\n290203 010203 888.88 John Doe club fee Feb2003’
*`payments completed t\club fee`
Returns ‘010303 010203 888.88 John Tan club fee Feb2003\n290203 010203 888.88 John Doe club fee Feb2003’
*`payments pending t\Mar2003`
Returns ‘No pending payments.’

=== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order. +
Format: `history`

[NOTE]
====
Pressing the kbd:[&uarr;] and kbd:[&darr;] arrows will display the previous and next input respectively in the command box.
====

// tag::undoredo[]
=== Undoing previous command : `undo`

Restores ClubManager to the state before the previous _undoable_ command was executed. +
Format: `undo`

[NOTE]
====
Undoable commands: those commands that modify ClubManager's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `delete 1` +
`list` +
`undo` (reverses the `delete 1` command) +

* `list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

=== Redoing the previously undone command : `redo`

Reverses the most recent `undo` command. +
Format: `redo`

Examples:

* `delete 1` +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +

* `delete 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

=== Clearing all entries : `clear`

Clears all entries from ClubManager. +
Format: `clear`

=== Checking the statistics of members : `check`

Check the statistics of the club members such as previous attendance rate or makeup of members. +
Format: `check attendance` or ‘check makeup’

****
* Check some status of the members such as `attendance` or `makeup`
* `attendance` for each member is calculated by the ratio of the number of events attended +
to the number of signups
* `makeup` of the members gives a chart of membership percentage of students from +
different academic year.
****

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

ClubManager data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

// tag::dataencryption[]
=== Encrypting data files `[coming in v2.0]`

_{explain how the user can enable/disable data encryption}_
// end::dataencryption[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous ClubManager folder.

== Command Summary

* *Add* `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...` +
e.g. `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague`
* *Clear* : `clear`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Edit* : `edit INDEX [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [t/TAG]...` +
e.g. `edit 2 n/James Lee e/jameslee@example.com`
* *Find* : `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find James Jake`
* *List* : `list`
* *Help* : `help`
* *History* : `history`
* *Undo* : `undo`
* *Redo* : `redo`

Mockups:

Calendar Page Mockup

Statistics Page Mockup


Add Member
Name, Matric No, Email, Phone, Year, IC, Role
Import and export data from forms
Delete Member
Edit Member (option e.g. phone, name, etc. individually)
Sort Member List
List Members
View Member
Clear Member List
Create Activity
Edit Activity (activity details, description)
Add member to activity
Delete member from activity
Delete Activity 
View Activity List
Sort Activity List
Payment Tracking
request payment, 
pending payments, 
receive payment, 
completed payments;
Attendance Rate (sign up for events and actually go)
Statistics (members per year etc, members age range)
Display Calendar (v2.0 or something)

Add any features you think should be in our addressbook
Or if anything looks weird please sound off

Members List: Joel
Activity List: Minern
Payment: Melissa 
Statistics: Yiqing
Calendar/ Import Export: Kevin


