= AddressBook Level 4 - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S2-W09-2/main

By: `Team W9-02 (HealthHub)`      Since: `Jan 2019`      Licence: `MIT`

== Introduction

HealthHub is a application that allows users to add, manage and close requests from patients for health services. AB4 provides a *Graphical User Interface* for administrative staff of health organisations and hospitals to manage requests from all potential home stay patients, and is also *optimized for those who prefer to work with a Command Line Interface* (CLI). +
Looking to improve and ease management of requests from cusomters and patients? Look no further, HealthHub provides all the utility and functions you need to streamline your workflow. Interested? Jump to the <<Quick Start>> to get started. Enjoy!

== Quick Start

.  Ensure you have Java version `9` or later installed in your Computer.
.  Additional installation guides will be added further into the project.

.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`list`* : lists all requests
* **`add`**`i/3 n/John Doe p/98765432 a/John street, block 123, #01-01` : adds a patient named `John Doe` to the application.
* **`delete`**`t/R n/4` : deletes the 4th request shown by the list command
* *`exit`* : exits the app

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

Note that the current application is a work in progress. The following description of the features and commands are prototypes and specific details and implementation may vary over the course of the project.

====
*Command Format*

* Words in `<tags>` are the parameters to be supplied by the user e.g. in `add n/<name>`, `<name>` is a parameter which can be used as `add n/John Doe`.
* Items in square brackets are optional e.g `n/<name> [s/<specialisation>]` can be used as `n/John Doe s/Gynaecology` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[s/<specialisation>]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/<name> p/<phone_number>`, `p/<phonenumber> n/<name>` is also acceptable.
====

=== Viewing help : `help`

Format: `help`

Lists all available commands, their parameters and their function.

=== Listing all requests/health workers/patients : `list`

Shows a list of all requests, health workers or patients based on the `<type>` parameters . +
Format: `list <type>`

Example:

* `list 1` lists all requests stored in the system, and their corresponding details
* `list 2` lists all health workers stored in the system, and the skills and certifications they posses

=== Adding a request/health worker/patient: `add`

Adds a request, health worker or patient to the application based on the `<type>` parameter accepted +
Format: `add <type> <additional_parameters>...` +
Types:

* 1: Adding a request `add 1 n/<patient_name> c/<condition> d/<date> t/time`
* 2: Adding a health worker `add 2 n/<worker_name> i/<NRIC> n/<phone_number> s/<specialisation>...`
* 3: Adding a patient `add 3 n/<patient_name> i/<NRIC> n/<phone_number>`

Examples:

* `add 1 n/Lucas Choong c/Arthritis d/05/02/2019 t/1400`
* `add 2 n/John Doe p/98765432 a/John street, block 123, #01-01`
* `add 3 n/Betsy Crowe t/friend a/Newgate Prison p/1234567 t/criminal`

=== Editing a request/health worker/patient : `edit`

Edits a request, health worker or patient to the application based on the `<type>` parameter accepted. +
Format: `edit <type> <index> <additional_parameters>...` +
Types:

* 1: Edit a request `edit 1 <index> n/<patient_name> c/<condition> d/<date> t/time`
* 2: Edit a health worker `edit 2 <index> n/<worker_name> i/<NRIC> n/<phone_number> s/<specialisation>...`
* 3: Edit a patient `edit 3 <index> n/<patient_name> i/<NRIC> n/<phone_number>`

Notes:

****
* Edits the corresponding request/health worker/patient at the specified `<index>`. The index refers to the index number shown in the displayed person list. The index *must be a positive integer* 1, 2, 3, ...
* Each of the additional parameters must be filled up unless optional.
* Existing values will be updated to the input values.
* When editing specialisations, the existing specialisations of the person will be removed i.e adding of specialisation is not cumulative.
* You can remove all the person's speciailisation by typing `s/` without specifying any parameters after it.
****

Examples:

* `edit 2 1 p/91234567 n/John Doe` +
Edits the phone number and name of the 1st health worker to be `91234567` and `John Doe` respectively. +
* `edit 3 2 n/Betsy Crower` +
Edits the name of the 2nd patient to be `Betsy Crower`. +

=== Locating request/health worker/patient by name: `find`

Finds requests/health workers/patients whose names contain any of the given keywords. For requests, the requests containing the patient name with the keywords specified will be displayed. +
Format: `find <type> <keyword> [<more_keywords>]...` +
Types:

* 1: Find a request `find 1 <keyword> [<more_keywords>]`
* 2: Find a health worker `find 2 <keyword> [<more_keywords>]`
* 3: Find a patient `find 3 <keyword> [<more_keywords>]`

Notes:

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Persons matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****

Examples:

* `find 3 John` +
Returns patients named `john` and `John Doe`
* `find 1 Betsy Tim John` +
Returns requests that involved patients whose names are `Betsy`, `Tim`, or `John`

=== Deleting a request/health worker/patient : `delete`

Deletes a request, health worker or patient to the application based on the `<type>` parameter accepted. +
Format: `delete <type> <index>` +
Types:

* 1: Edit a request `edit 1 <index>`
* 2: Edit a health worker `edit 2`
* 3: Edit a patient `edit 3 <index>`

Notes:

****
* Deletes the corresponding request/health worker/patient at the specified `<index>`.
* The index refers to the index number shown in the displayed person list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `list` +
`delete 1 2` +
Deletes the 2nd request in the application.

* `delete 3 1` +
Deletes the 1st patient in the results of the `find` command.

=== Assigning a health worker to an existing open request : `assign`

Assigns a health worker in the system to an existing open request. +
Format: `assign p/<patient_name> h/<health_worker_name>`

****
* Health worker that is assigned must be available at the current time stated by the request.
* Health worker must have the necessary skillset and certifications that allow him to be able to take up the corresponding request.
****

Examples:

* `assign p/John Doe h/Dog Tor` +
Assigns the health worker named Dog Tor to a request containing a patient with the name John Doe.

=== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order. +
Format: `history`

[NOTE]
====
Pressing the kbd:[&uarr;] and kbd:[&darr;] arrows will display the previous and next input respectively in the command box.
====

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

Application data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Help* : `help`
* *List* : `list <type>`
* *Add* : `add <type> <additional_parameters>...`
* *Edit* : `edit <type> <index> <additional_parameters>...`
* *Find* : `find <type> <keyword> [<more_keywords>]...`
* *Delete* : `delete <type> <index>`
* *Assign* : `assign p/<patient_name> h/<health_worker_name>`
* *History* : `history`
